/**
 * Investment Component - Core Export
 *
 * Generated by Domain Index Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: investment
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

// Types (Domain layer with Date objects + API operation types)
export * from "./types/index.js";

// Repository Interfaces (only if domain has repositories)
export * from "./repositories/index.js";

// ❌ Handlers removed from core per DDD principles
// Handlers are application/inbound concerns and belong in services or api-server
// Handler interfaces should be defined locally in handler implementations or replaced with use cases

// ❌ Converters removed from core per DDD principles
// Converters are application layer concerns and belong in services layer

// Schemas (Zod schemas from OpenAPI) - domain-specific export name
export { schemas as investmentSchemas } from "./schemas/investment.schemas.js";
