/**
 * ListDataBlocker DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: readiness
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListDataBlockersParams } from "@formulary/core/readiness";

export function createListDataBlockerRequest(overrides: Partial<ListDataBlockersParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
