/**
 * Routes for Claim
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: benefits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { claimBenefit } from "../handlers/claim.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function claimRoutes(fastify: FastifyInstance) {
  // POST /v1/benefits/claims (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/benefits/claims",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getBenefitsDependenciesForRequest();
        await claimBenefit(request, reply, deps);
      });
    }
  );


}
