/**
 * Routes for ConductGate
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { openConductGateReview } from "../handlers/conduct-gate.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function conductGateRoutes(fastify: FastifyInstance) {
  // POST /v1/candidates/{candidateId}/conduct-gate (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/candidates/:candidateId/conduct-gate",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { candidateId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getGatesDependenciesForRequest();
        await openConductGateReview(request, reply, deps);
      });
    }
  );


}
