/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { conductGateRoutes } from "./conduct-gate.routes.js";
export { decisionRoutes } from "./decision.routes.js";
export { featureRiskFindingRoutes } from "./feature-risk-finding.routes.js";
