/**
 * Claim DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: benefits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Claim DTOs
 *
 * DDD: Application DTOs for Claim use cases.
 */

import type { ClaimBenefitRequestInput } from "@formulary/core/benefits/types";

export type ClaimBenefitInput = ClaimBenefitRequestInput;

export type ClaimBenefitOutput = {};
