/**
 * GetDataReadinessVerdict handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: readiness
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getDataReadinessVerdict } from "@formulary/api-server/domains/readiness/handlers";
import type { ReadinessDDDDependencies } from "@formulary/api-server/domains/readiness";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@formulary/tests/shared";
import { READINESS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetDataReadinessVerdict", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ReadinessDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ReadinessDDDDependencies>(
      READINESS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetDataReadinessVerdict, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { candidateId: entity.id };

    await getDataReadinessVerdict(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetDataReadinessVerdict.execute).toHaveBeenCalledWith(expect.objectContaining({ candidateId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { candidateId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetDataReadinessVerdict, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getDataReadinessVerdict(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
