/**
 * IssueDataReadinessVerdict handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: readiness
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { issueDataReadinessVerdict } from "@formulary/api-server/domains/readiness/handlers";
import type { ReadinessDDDDependencies } from "@formulary/api-server/domains/readiness";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@formulary/tests/shared";
import { READINESS_USE_CASES } from "../__factories__/use-cases.js";

describe("IssueDataReadinessVerdict", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ReadinessDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ReadinessDDDDependencies>(
      READINESS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeIssueDataReadinessVerdict, "execute").mockResolvedValue(useCaseResult);

    await issueDataReadinessVerdict(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeIssueDataReadinessVerdict.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
