/**
 * DataBlockerRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: readiness
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DataBlockerRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements DataBlockerRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  DataBlockerRepository,
} from "@formulary/services/readiness";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { DataBlockerRepositoryDdb } from "./data-blocker-repository.ddb.js";

/**
 * DataBlockerRepositoryAdapter
 *
 * Implements DataBlockerRepository port for infrastructure layer.
 */
export class DataBlockerRepositoryAdapter implements DataBlockerRepository {
  private readonly ddb: DataBlockerRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new DataBlockerRepositoryDdb(this.dynamoClient);
  }

  async listDataBlockers(input: Parameters<DataBlockerRepository['listDataBlockers']>[0]): Promise<Awaited<ReturnType<DataBlockerRepository['listDataBlockers']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listDataBlockers(input);
  }
}
