/**
 * ReadinessRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: readiness
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ReadinessRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ReadinessRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ReadinessRepository,
} from "@formulary/services/readiness";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ReadinessRepositoryDdb } from "./readiness-repository.ddb.js";

/**
 * ReadinessRepositoryAdapter
 *
 * Implements ReadinessRepository port for infrastructure layer.
 */
export class ReadinessRepositoryAdapter implements ReadinessRepository {
  private readonly ddb: ReadinessRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ReadinessRepositoryDdb(this.dynamoClient);
  }

  async issueDataReadinessVerdict(input: Parameters<ReadinessRepository['issueDataReadinessVerdict']>[0]): Promise<Awaited<ReturnType<ReadinessRepository['issueDataReadinessVerdict']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.issueDataReadinessVerdict(input);
  }

  async getDataReadinessVerdict(input: Parameters<ReadinessRepository['getDataReadinessVerdict']>[0]): Promise<Awaited<ReturnType<ReadinessRepository['getDataReadinessVerdict']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getDataReadinessVerdict(input);
  }
}
