/**
 * Handlers for Readiness
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: readiness
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ReadinessDomainModule } from "../dependencies/readiness-ddd.dependencies.js";
import type { GetDataReadinessVerdictInput, IssueDataReadinessVerdictInput } from "@formulary/services/readiness";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/candidates/{candidateId}/readiness
 * Operation: issueDataReadinessVerdict
 */
export async function issueDataReadinessVerdict(
  request: FastifyRequest<{ Params: { candidateId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ReadinessDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input = {
    candidateId: request.params.candidateId,
    ...(request.body ?? {}),
  } as IssueDataReadinessVerdictInput;
  const result = await deps.useCases.readinesses.get.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/candidates/{candidateId}/readiness
 * Operation: getDataReadinessVerdict
 */
export async function getDataReadinessVerdict(
  request: FastifyRequest<{ Params: { candidateId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ReadinessDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input = {
    candidateId: request.params.candidateId,
  } as GetDataReadinessVerdictInput;
  const result = await deps.useCases.readinesses.get.execute(input);
  return reply.code(200).send(result);
}


