/**
 * Investment DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: investment
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Investment DTOs
 *
 * DDD: Application DTOs for Investment use cases.
 */

import type { ApproveInvestmentParams, ApproveInvestmentRequestInput } from "@formulary/core/investment/types";

export type ApproveInvestmentInput = ApproveInvestmentParams & ApproveInvestmentRequestInput;

export type ApproveInvestmentOutput = {};
