/**
 * ListAnalogue DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: portfolio
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListAnalogueCasesParams } from "@formulary/core/portfolio";

export function createListAnalogueRequest(overrides: Partial<ListAnalogueCasesParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
