/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/registry/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List registered production models */
        get: operations["listModelRegistrations"];
        put?: never;
        /** Register a production model */
        post: operations["registerModel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/registry/data-dependencies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List registered data dependencies */
        get: operations["listDataDependencies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Opaque keyset cursor */
        Cursor: string;
        /** @default 50 */
        Limit: number;
        /** @enum {string} */
        ModelFamily: "speech_voice_recognition" | "sentiment_detection" | "recommendation_engine" | "text_analytics_nlp" | "pattern_anomaly_detection" | "automatic_decision_management" | "natural_language_generation" | "object_detection" | "biometrics";
        /** @description RFC 7807 Problem Details (provisional mapping for gateway errors). */
        Problem: {
            /**
             * Format: uri
             * @description URI reference identifying the problem type.
             */
            type?: string;
            /** @description Short human-readable summary. */
            title?: string;
            /** @description HTTP status code. */
            status?: number;
            /** @description Human-readable explanation specific to this occurrence. */
            detail?: string;
            /**
             * Format: uri
             * @description URI reference identifying this occurrence.
             */
            instance?: string;
            /** @description Optional machine-readable error code from the gateway. */
            code?: string;
        } & {
            [key: string]: unknown;
        };
        /** @description Prefixed use-case candidate id */
        CandidateId: string;
        /**
         * @description Declared regulated touchpoints that trigger the conduct gate
         * @enum {string}
         */
        Touchpoint: "rating_factor" | "renewal_price" | "underwriting_acceptance" | "claims_decision" | "fraud_referral" | "reserving_input" | "marketing_targeting" | "none";
        ModelRegistration: {
            id: string;
            name: string;
            /** @enum {string} */
            modelFamily: "speech_voice_recognition" | "sentiment_detection" | "recommendation_engine" | "text_analytics_nlp" | "pattern_anomaly_detection" | "automatic_decision_management" | "natural_language_generation" | "object_detection" | "biometrics";
            ownerId: string;
            candidateIds?: string[];
            dataDependencyIds?: string[];
            conductGateReviewId?: string;
            touchpoints?: ("rating_factor" | "renewal_price" | "underwriting_acceptance" | "claims_decision" | "fraud_referral" | "reserving_input" | "marketing_targeting" | "none")[];
            inOwnRiskAndSolvencyScope?: boolean;
            /** Format: date-time */
            registeredAt?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ModelRegistrationListData: {
            items: {
                id: string;
                name: string;
                /** @enum {string} */
                modelFamily: "speech_voice_recognition" | "sentiment_detection" | "recommendation_engine" | "text_analytics_nlp" | "pattern_anomaly_detection" | "automatic_decision_management" | "natural_language_generation" | "object_detection" | "biometrics";
                ownerId: string;
                candidateIds?: string[];
                dataDependencyIds?: string[];
                conductGateReviewId?: string;
                touchpoints?: ("rating_factor" | "renewal_price" | "underwriting_acceptance" | "claims_decision" | "fraud_referral" | "reserving_input" | "marketing_targeting" | "none")[];
                inOwnRiskAndSolvencyScope?: boolean;
                /** Format: date-time */
                registeredAt?: string;
                /** Format: date-time */
                createdAt?: string;
                /** Format: date-time */
                updatedAt?: string;
            }[];
            nextCursor?: string;
        };
        ResponseMeta: {
            /**
             * Format: uuid
             * @description Correlation id for this HTTP request.
             */
            requestId?: string;
            /** @description Optional end-to-end correlation id. */
            correlationId?: string;
            /**
             * Format: date-time
             * @description Server time when the payload was produced.
             */
            generatedAt?: string;
        };
        ModelRegistrationListResponse: {
            data: {
                items: {
                    id: string;
                    name: string;
                    /** @enum {string} */
                    modelFamily: "speech_voice_recognition" | "sentiment_detection" | "recommendation_engine" | "text_analytics_nlp" | "pattern_anomaly_detection" | "automatic_decision_management" | "natural_language_generation" | "object_detection" | "biometrics";
                    ownerId: string;
                    candidateIds?: string[];
                    dataDependencyIds?: string[];
                    conductGateReviewId?: string;
                    touchpoints?: ("rating_factor" | "renewal_price" | "underwriting_acceptance" | "claims_decision" | "fraud_referral" | "reserving_input" | "marketing_targeting" | "none")[];
                    inOwnRiskAndSolvencyScope?: boolean;
                    /** Format: date-time */
                    registeredAt?: string;
                    /** Format: date-time */
                    createdAt?: string;
                    /** Format: date-time */
                    updatedAt?: string;
                }[];
                nextCursor?: string;
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
        ModelRegistrationCreate: {
            name: string;
            /** @enum {string} */
            modelFamily: "speech_voice_recognition" | "sentiment_detection" | "recommendation_engine" | "text_analytics_nlp" | "pattern_anomaly_detection" | "automatic_decision_management" | "natural_language_generation" | "object_detection" | "biometrics";
            ownerId: string;
            candidateIds?: string[];
            dataDependencyIds?: string[];
            conductGateReviewId?: string;
            touchpoints?: ("rating_factor" | "renewal_price" | "underwriting_acceptance" | "claims_decision" | "fraud_referral" | "reserving_input" | "marketing_targeting" | "none")[];
        };
        ModelRegistrationResponse: {
            data: {
                id: string;
                name: string;
                /** @enum {string} */
                modelFamily: "speech_voice_recognition" | "sentiment_detection" | "recommendation_engine" | "text_analytics_nlp" | "pattern_anomaly_detection" | "automatic_decision_management" | "natural_language_generation" | "object_detection" | "biometrics";
                ownerId: string;
                candidateIds?: string[];
                dataDependencyIds?: string[];
                conductGateReviewId?: string;
                touchpoints?: ("rating_factor" | "renewal_price" | "underwriting_acceptance" | "claims_decision" | "fraud_referral" | "reserving_input" | "marketing_targeting" | "none")[];
                inOwnRiskAndSolvencyScope?: boolean;
                /** Format: date-time */
                registeredAt?: string;
                /** Format: date-time */
                createdAt?: string;
                /** Format: date-time */
                updatedAt?: string;
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
        /**
         * @description The y term of the formula
         * @enum {string}
         */
        DataType: "company" | "public" | "third_party" | "customer";
        RegisteredDataDependency: {
            id: string;
            /**
             * @description The y term of the formula
             * @enum {string}
             */
            dataType: "company" | "public" | "third_party" | "customer";
            name: string;
            structured?: boolean;
            /** @enum {string} */
            permissionBasis?: "contractual" | "consent" | "legitimate_interest" | "licensed" | "public_domain" | "not_established";
            onwardTransferTerms?: string;
            /** Format: date */
            permissionRenewalDate?: string;
            /** Format: float */
            expectedBookCoverage?: number;
            ownerId?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        RegisteredDataDependencyListData: {
            items: {
                id: string;
                /**
                 * @description The y term of the formula
                 * @enum {string}
                 */
                dataType: "company" | "public" | "third_party" | "customer";
                name: string;
                structured?: boolean;
                /** @enum {string} */
                permissionBasis?: "contractual" | "consent" | "legitimate_interest" | "licensed" | "public_domain" | "not_established";
                onwardTransferTerms?: string;
                /** Format: date */
                permissionRenewalDate?: string;
                /** Format: float */
                expectedBookCoverage?: number;
                ownerId?: string;
                /** Format: date-time */
                createdAt?: string;
                /** Format: date-time */
                updatedAt?: string;
            }[];
            nextCursor?: string;
        };
        RegisteredDataDependencyListResponse: {
            data: {
                items: {
                    id: string;
                    /**
                     * @description The y term of the formula
                     * @enum {string}
                     */
                    dataType: "company" | "public" | "third_party" | "customer";
                    name: string;
                    structured?: boolean;
                    /** @enum {string} */
                    permissionBasis?: "contractual" | "consent" | "legitimate_interest" | "licensed" | "public_domain" | "not_established";
                    onwardTransferTerms?: string;
                    /** Format: date */
                    permissionRenewalDate?: string;
                    /** Format: float */
                    expectedBookCoverage?: number;
                    ownerId?: string;
                    /** Format: date-time */
                    createdAt?: string;
                    /** Format: date-time */
                    updatedAt?: string;
                }[];
                nextCursor?: string;
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
    };
    responses: {
        /** @description Error (RFC 7807 Problem Details) */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        /** @description Missing or invalid API key */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
    };
    parameters: {
        Cursor: string;
        Limit: number;
        /**
         * @description Client-supplied key for safe retries on mutating POSTs (≤128 chars).
         *     Replay with the same key and body returns the original result; different
         *     body with the same key yields 409.
         */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listModelRegistrations: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
                modelFamily?: "speech_voice_recognition" | "sentiment_detection" | "recommendation_engine" | "text_analytics_nlp" | "pattern_anomaly_detection" | "automatic_decision_management" | "natural_language_generation" | "object_detection" | "biometrics";
                unowned?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Registered production models with owners and dependencies */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: {
                                id: string;
                                name: string;
                                /** @enum {string} */
                                modelFamily: "speech_voice_recognition" | "sentiment_detection" | "recommendation_engine" | "text_analytics_nlp" | "pattern_anomaly_detection" | "automatic_decision_management" | "natural_language_generation" | "object_detection" | "biometrics";
                                ownerId: string;
                                candidateIds?: string[];
                                dataDependencyIds?: string[];
                                conductGateReviewId?: string;
                                touchpoints?: ("rating_factor" | "renewal_price" | "underwriting_acceptance" | "claims_decision" | "fraud_referral" | "reserving_input" | "marketing_targeting" | "none")[];
                                inOwnRiskAndSolvencyScope?: boolean;
                                /** Format: date-time */
                                registeredAt?: string;
                                /** Format: date-time */
                                createdAt?: string;
                                /** Format: date-time */
                                updatedAt?: string;
                            }[];
                            nextCursor?: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    registerModel: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-supplied key for safe retries on mutating POSTs (≤128 chars).
                 *     Replay with the same key and body returns the original result; different
                 *     body with the same key yields 409.
                 */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /** @enum {string} */
                    modelFamily: "speech_voice_recognition" | "sentiment_detection" | "recommendation_engine" | "text_analytics_nlp" | "pattern_anomaly_detection" | "automatic_decision_management" | "natural_language_generation" | "object_detection" | "biometrics";
                    ownerId: string;
                    candidateIds?: string[];
                    dataDependencyIds?: string[];
                    conductGateReviewId?: string;
                    touchpoints?: ("rating_factor" | "renewal_price" | "underwriting_acceptance" | "claims_decision" | "fraud_referral" | "reserving_input" | "marketing_targeting" | "none")[];
                };
            };
        };
        responses: {
            /** @description Model registered against its use cases and gate outcome */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            name: string;
                            /** @enum {string} */
                            modelFamily: "speech_voice_recognition" | "sentiment_detection" | "recommendation_engine" | "text_analytics_nlp" | "pattern_anomaly_detection" | "automatic_decision_management" | "natural_language_generation" | "object_detection" | "biometrics";
                            ownerId: string;
                            candidateIds?: string[];
                            dataDependencyIds?: string[];
                            conductGateReviewId?: string;
                            touchpoints?: ("rating_factor" | "renewal_price" | "underwriting_acceptance" | "claims_decision" | "fraud_referral" | "reserving_input" | "marketing_targeting" | "none")[];
                            inOwnRiskAndSolvencyScope?: boolean;
                            /** Format: date-time */
                            registeredAt?: string;
                            /** Format: date-time */
                            createdAt?: string;
                            /** Format: date-time */
                            updatedAt?: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    listDataDependencies: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
                dataType?: "company" | "public" | "third_party" | "customer";
                permissionExpiringWithinDays?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dependencies with permission basis and renewal dates */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: {
                                id: string;
                                /**
                                 * @description The y term of the formula
                                 * @enum {string}
                                 */
                                dataType: "company" | "public" | "third_party" | "customer";
                                name: string;
                                structured?: boolean;
                                /** @enum {string} */
                                permissionBasis?: "contractual" | "consent" | "legitimate_interest" | "licensed" | "public_domain" | "not_established";
                                onwardTransferTerms?: string;
                                /** Format: date */
                                permissionRenewalDate?: string;
                                /** Format: float */
                                expectedBookCoverage?: number;
                                ownerId?: string;
                                /** Format: date-time */
                                createdAt?: string;
                                /** Format: date-time */
                                updatedAt?: string;
                            }[];
                            nextCursor?: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
