/**
 * ExecuteSetValuePosition - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: candidates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteSetValuePosition Use Case
 *
 * DDD: Application use case for update ValuePosition.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { SetValuePositionInput, SetValuePositionOutput } from "../dto/value-position.dto";
import type { ExecutionContextService, IdGeneratorService } from "@formulary/services/_shared/index.js";
import type { ValuePositionRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanUpdate } from "../policies/can-update.policy";
export class ExecuteSetValuePosition {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly valuePosition: ValuePositionRepository
  ) {}

  async execute(input: SetValuePositionInput): Promise<SetValuePositionOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.candId();

    // All field names extracted from OpenAPI spec
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).candidateId) {
      throw new ValidationError("candidateId is required");
    }
    const candidateId = (input as any).candidateId;
    // No get/list operation for this resource - call update directly
    // Check policy
    if (!CanUpdate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Update entity via repository (pass correlation ID for response meta)
    const updated = await this.valuePosition.setValuePosition({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return updated as SetValuePositionOutput;
  }
}
