/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/candidates/{candidateId}/conduct-gate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidateId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Open conduct gate review */
        post: operations["openConductGateReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/conduct-gate-reviews/{reviewId}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reviewId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record conduct gate decision */
        post: operations["decideConductGate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/conduct-gate-reviews/{reviewId}/feature-risk-findings": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reviewId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Raise feature risk finding */
        post: operations["raiseFeatureRiskFinding"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Prefixed use-case candidate id */
        CandidateId: string;
        /**
         * @description Declared regulated touchpoints that trigger the conduct gate
         * @enum {string}
         */
        Touchpoint: "rating_factor" | "renewal_price" | "underwriting_acceptance" | "claims_decision" | "fraud_referral" | "reserving_input" | "marketing_targeting" | "none";
        ConductGateReviewCreate: {
            triggeredBy: ("rating_factor" | "renewal_price" | "underwriting_acceptance" | "claims_decision" | "fraud_referral" | "reserving_input" | "marketing_targeting" | "none")[];
            proposedFeatures: string[];
            actuarialReviewerId?: string;
            /** @description How a policyholder reaches human review of the decision */
            humanReviewRoute?: string;
        };
        /** @description RFC 7807 Problem Details (provisional mapping for gateway errors). */
        Problem: {
            /**
             * Format: uri
             * @description URI reference identifying the problem type.
             */
            type?: string;
            /** @description Short human-readable summary. */
            title?: string;
            /** @description HTTP status code. */
            status?: number;
            /** @description Human-readable explanation specific to this occurrence. */
            detail?: string;
            /**
             * Format: uri
             * @description URI reference identifying this occurrence.
             */
            instance?: string;
            /** @description Optional machine-readable error code from the gateway. */
            code?: string;
        } & {
            [key: string]: unknown;
        };
        ReviewId: string;
        FeatureRiskFinding: {
            /** @example residential_postcode_cluster */
            feature: string;
            /** @enum {string} */
            riskType: "proxy_for_protected_characteristic" | "price_sensitivity_signal" | "unexplainable_to_policyholder" | "provenance_unverifiable" | "not_permitted_in_rating";
            /** @enum {string} */
            severity?: "low" | "medium" | "high" | "blocking";
            mitigation?: string;
            raisedBy?: string;
        };
        ConductGateReview: {
            id: string;
            /** @description Prefixed use-case candidate id */
            candidateId: string;
            triggeredBy: ("rating_factor" | "renewal_price" | "underwriting_acceptance" | "claims_decision" | "fraud_referral" | "reserving_input" | "marketing_targeting" | "none")[];
            proposedFeatures?: string[];
            /** @enum {string} */
            outcome: "open" | "approved" | "approved_with_conditions" | "withheld";
            officerId?: string;
            actuarialReviewerId?: string;
            conditions?: string[];
            rationale?: string;
            findings?: {
                /** @example residential_postcode_cluster */
                feature: string;
                /** @enum {string} */
                riskType: "proxy_for_protected_characteristic" | "price_sensitivity_signal" | "unexplainable_to_policyholder" | "provenance_unverifiable" | "not_permitted_in_rating";
                /** @enum {string} */
                severity?: "low" | "medium" | "high" | "blocking";
                mitigation?: string;
                raisedBy?: string;
            }[];
            /** Format: date-time */
            decidedAt?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ResponseMeta: {
            /**
             * Format: uuid
             * @description Correlation id for this HTTP request.
             */
            requestId?: string;
            /** @description Optional end-to-end correlation id. */
            correlationId?: string;
            /**
             * Format: date-time
             * @description Server time when the payload was produced.
             */
            generatedAt?: string;
        };
        ConductGateReviewResponse: {
            data: {
                id: string;
                /** @description Prefixed use-case candidate id */
                candidateId: string;
                triggeredBy: ("rating_factor" | "renewal_price" | "underwriting_acceptance" | "claims_decision" | "fraud_referral" | "reserving_input" | "marketing_targeting" | "none")[];
                proposedFeatures?: string[];
                /** @enum {string} */
                outcome: "open" | "approved" | "approved_with_conditions" | "withheld";
                officerId?: string;
                actuarialReviewerId?: string;
                conditions?: string[];
                rationale?: string;
                findings?: {
                    /** @example residential_postcode_cluster */
                    feature: string;
                    /** @enum {string} */
                    riskType: "proxy_for_protected_characteristic" | "price_sensitivity_signal" | "unexplainable_to_policyholder" | "provenance_unverifiable" | "not_permitted_in_rating";
                    /** @enum {string} */
                    severity?: "low" | "medium" | "high" | "blocking";
                    mitigation?: string;
                    raisedBy?: string;
                }[];
                /** Format: date-time */
                decidedAt?: string;
                /** Format: date-time */
                createdAt?: string;
                /** Format: date-time */
                updatedAt?: string;
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
        ConductGateDecision: {
            officerId: string;
            /** @enum {string} */
            outcome: "approved" | "approved_with_conditions" | "withheld";
            rationale: string;
            conditions?: string[];
        };
        FeatureRiskFindingCreate: {
            feature: string;
            /** @enum {string} */
            riskType: "proxy_for_protected_characteristic" | "price_sensitivity_signal" | "unexplainable_to_policyholder" | "provenance_unverifiable" | "not_permitted_in_rating";
            /** @enum {string} */
            severity: "low" | "medium" | "high" | "blocking";
            mitigation?: string;
        };
        FeatureRiskFindingResponse: {
            data: {
                /** @example residential_postcode_cluster */
                feature: string;
                /** @enum {string} */
                riskType: "proxy_for_protected_characteristic" | "price_sensitivity_signal" | "unexplainable_to_policyholder" | "provenance_unverifiable" | "not_permitted_in_rating";
                /** @enum {string} */
                severity?: "low" | "medium" | "high" | "blocking";
                mitigation?: string;
                raisedBy?: string;
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
    };
    responses: {
        /** @description Error (RFC 7807 Problem Details) */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        /** @description Missing or invalid API key */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
    };
    parameters: {
        CandidateId: string;
        /**
         * @description Client-supplied key for safe retries on mutating POSTs (≤128 chars).
         *     Replay with the same key and body returns the original result; different
         *     body with the same key yields 409.
         */
        IdempotencyKey: string;
        ReviewId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    openConductGateReview: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-supplied key for safe retries on mutating POSTs (≤128 chars).
                 *     Replay with the same key and body returns the original result; different
                 *     body with the same key yields 409.
                 */
                "Idempotency-Key": string;
            };
            path: {
                candidateId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    triggeredBy: ("rating_factor" | "renewal_price" | "underwriting_acceptance" | "claims_decision" | "fraud_referral" | "reserving_input" | "marketing_targeting" | "none")[];
                    proposedFeatures: string[];
                    actuarialReviewerId?: string;
                    /** @description How a policyholder reaches human review of the decision */
                    humanReviewRoute?: string;
                };
            };
        };
        responses: {
            /** @description Conduct review opened for the declared touchpoints */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            /** @description Prefixed use-case candidate id */
                            candidateId: string;
                            triggeredBy: ("rating_factor" | "renewal_price" | "underwriting_acceptance" | "claims_decision" | "fraud_referral" | "reserving_input" | "marketing_targeting" | "none")[];
                            proposedFeatures?: string[];
                            /** @enum {string} */
                            outcome: "open" | "approved" | "approved_with_conditions" | "withheld";
                            officerId?: string;
                            actuarialReviewerId?: string;
                            conditions?: string[];
                            rationale?: string;
                            findings?: {
                                /** @example residential_postcode_cluster */
                                feature: string;
                                /** @enum {string} */
                                riskType: "proxy_for_protected_characteristic" | "price_sensitivity_signal" | "unexplainable_to_policyholder" | "provenance_unverifiable" | "not_permitted_in_rating";
                                /** @enum {string} */
                                severity?: "low" | "medium" | "high" | "blocking";
                                mitigation?: string;
                                raisedBy?: string;
                            }[];
                            /** Format: date-time */
                            decidedAt?: string;
                            /** Format: date-time */
                            createdAt?: string;
                            /** Format: date-time */
                            updatedAt?: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    decideConductGate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reviewId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    officerId: string;
                    /** @enum {string} */
                    outcome: "approved" | "approved_with_conditions" | "withheld";
                    rationale: string;
                    conditions?: string[];
                };
            };
        };
        responses: {
            /** @description Gate decision recorded and binding on build */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            /** @description Prefixed use-case candidate id */
                            candidateId: string;
                            triggeredBy: ("rating_factor" | "renewal_price" | "underwriting_acceptance" | "claims_decision" | "fraud_referral" | "reserving_input" | "marketing_targeting" | "none")[];
                            proposedFeatures?: string[];
                            /** @enum {string} */
                            outcome: "open" | "approved" | "approved_with_conditions" | "withheld";
                            officerId?: string;
                            actuarialReviewerId?: string;
                            conditions?: string[];
                            rationale?: string;
                            findings?: {
                                /** @example residential_postcode_cluster */
                                feature: string;
                                /** @enum {string} */
                                riskType: "proxy_for_protected_characteristic" | "price_sensitivity_signal" | "unexplainable_to_policyholder" | "provenance_unverifiable" | "not_permitted_in_rating";
                                /** @enum {string} */
                                severity?: "low" | "medium" | "high" | "blocking";
                                mitigation?: string;
                                raisedBy?: string;
                            }[];
                            /** Format: date-time */
                            decidedAt?: string;
                            /** Format: date-time */
                            createdAt?: string;
                            /** Format: date-time */
                            updatedAt?: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    raiseFeatureRiskFinding: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reviewId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    feature: string;
                    /** @enum {string} */
                    riskType: "proxy_for_protected_characteristic" | "price_sensitivity_signal" | "unexplainable_to_policyholder" | "provenance_unverifiable" | "not_permitted_in_rating";
                    /** @enum {string} */
                    severity: "low" | "medium" | "high" | "blocking";
                    mitigation?: string;
                };
            };
        };
        responses: {
            /** @description Proxy or prohibited-practice finding raised against a feature */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            /** @example residential_postcode_cluster */
                            feature: string;
                            /** @enum {string} */
                            riskType: "proxy_for_protected_characteristic" | "price_sensitivity_signal" | "unexplainable_to_policyholder" | "provenance_unverifiable" | "not_permitted_in_rating";
                            /** @enum {string} */
                            severity?: "low" | "medium" | "high" | "blocking";
                            mitigation?: string;
                            raisedBy?: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
