/**
 * Handlers for Investment
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: investment
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { InvestmentDomainModule } from "../dependencies/investment-ddd.dependencies.js";
import type { ApproveInvestmentInput } from "@formulary/services/investment";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/candidates/{candidateId}/investment
 * Operation: approveInvestment
 */
export async function approveInvestment(
  request: FastifyRequest<{ Params: { candidateId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: InvestmentDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input = {
    candidateId: request.params.candidateId,
    ...(request.body ?? {}),
  } as ApproveInvestmentInput;
  const result = await deps.useCases.investments.create.execute(input);
  return reply.code(201).send(result);
}


