/**
 * Routes for DataDependency
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: registry
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { listDataDependencies } from "../handlers/data-dependency.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function dataDependencyRoutes(fastify: FastifyInstance) {
  // GET /v1/registry/data-dependencies (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/registry/data-dependencies",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getRegistryDependenciesForRequest();
        await listDataDependencies(request, reply, deps);
      });
    }
  );


}
