/**
 * AnalogueRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: portfolio
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AnalogueRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements AnalogueRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  AnalogueRepository,
} from "@formulary/services/portfolio";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { AnalogueRepositoryDdb } from "./analogue-repository.ddb.js";

/**
 * AnalogueRepositoryAdapter
 *
 * Implements AnalogueRepository port for infrastructure layer.
 */
export class AnalogueRepositoryAdapter implements AnalogueRepository {
  private readonly ddb: AnalogueRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new AnalogueRepositoryDdb(this.dynamoClient);
  }

  async listAnalogueCases(input: Parameters<AnalogueRepository['listAnalogueCases']>[0]): Promise<Awaited<ReturnType<AnalogueRepository['listAnalogueCases']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listAnalogueCases(input);
  }

  async recordAnalogueCase(input: Parameters<AnalogueRepository['recordAnalogueCase']>[0]): Promise<Awaited<ReturnType<AnalogueRepository['recordAnalogueCase']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.recordAnalogueCase(input);
  }
}
