/**
 * CommitteePackRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: portfolio
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CommitteePackRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements CommitteePackRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  CommitteePackRepository,
} from "@formulary/services/portfolio";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { CommitteePackRepositoryDdb } from "./committee-pack-repository.ddb.js";

/**
 * CommitteePackRepositoryAdapter
 *
 * Implements CommitteePackRepository port for infrastructure layer.
 */
export class CommitteePackRepositoryAdapter implements CommitteePackRepository {
  private readonly ddb: CommitteePackRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new CommitteePackRepositoryDdb(this.dynamoClient);
  }

  async getCommitteePack(input: Parameters<CommitteePackRepository['getCommitteePack']>[0]): Promise<Awaited<ReturnType<CommitteePackRepository['getCommitteePack']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getCommitteePack(input);
  }
}
