/**
 * Factories barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Factories Barrel Export
 *
 * Exports all entity and DTO factories for the gates domain.
 * Use these factories in tests to create test data.
 */

export { createFeatureRiskFinding } from "./feature-risk-finding/entity/feature-risk-finding.entity.factory.js";
