/**
 * Domain routes – register all domain route modules.
 *
 * AUTO-GENERATED by codegen (api_server_domain_routes). Do not edit by hand.
 * Rescans platform/api-server/src/domains and includes only domains that have
 * routes/index.ts and dependencies/{domain}-ddd.dependencies.ts.
 * Extension excludes/imports from x-codegen.api-server.extensions in OpenAPI YAML.
 */

import type { FastifyInstance } from "fastify";
import { registerDomainFromModule } from "./route-registration.js";

// Static imports so the bundle includes all domain route modules
import * as benefitsRoutes from "../../domains/benefits/routes/index.js";
import * as candidatesRoutes from "../../domains/candidates/routes/index.js";
import * as gatesRoutes from "../../domains/gates/routes/index.js";
import * as identityRoutes from "../../domains/identity/routes/index.js";
import * as investmentRoutes from "../../domains/investment/routes/index.js";
import * as portfolioRoutes from "../../domains/portfolio/routes/index.js";
import * as readinessRoutes from "../../domains/readiness/routes/index.js";
import * as registryRoutes from "../../domains/registry/routes/index.js";

const DOMAIN_MODULES: Array<{
  domain: string;
  mod: Record<string, unknown>;
  exclude?: string[];
}> = [
  { domain: "benefits", mod: benefitsRoutes },
  { domain: "candidates", mod: candidatesRoutes },
  { domain: "gates", mod: gatesRoutes },
  {
    domain: "identity", mod: identityRoutes,
    exclude: ["authRoutes", "loginRoutes", "logoutRoutes", "signupRoutes", "sessionRoutes", "refreshRoutes", "tokenRoutes", "profileRoutes"],
  },
  { domain: "investment", mod: investmentRoutes },
  { domain: "portfolio", mod: portfolioRoutes },
  { domain: "readiness", mod: readinessRoutes },
  { domain: "registry", mod: registryRoutes },
];

export async function registerAllDomainRoutes(
  fastify: FastifyInstance,
): Promise<void> {
  console.log("[DEBUG] Registering domain routes...");
  try {
    for (const { domain, mod, exclude } of DOMAIN_MODULES) {
      await registerDomainFromModule(fastify, domain, mod, exclude ?? []);
    }
    console.log("[DEBUG] ✅ All domain routes registered");
  } catch (error: unknown) {
    const err = error instanceof Error ? error : new Error(String(error));
    console.error("[DEBUG] ❌ Error registering domain routes:", err.message);
    if (err.stack) console.error(err.stack);
    throw error;
  }
}
