/**
 * DataBlocker DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: readiness
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DataBlocker DTOs
 *
 * DDD: Application DTOs for DataBlocker use cases.
 */

import type { ListDataBlockersParams } from "@formulary/core/readiness/types";

export type ListDataBlockersInput = ListDataBlockersParams;

export type ListDataBlockersOutput = {};
