/**
 * Handlers for Adjacency
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: candidates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { CandidatesDomainModule } from "../dependencies/candidates-ddd.dependencies.js";
import type { GetAdjacentUseCasesInput } from "@formulary/services/candidates";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/candidates/{candidateId}/adjacency
 * Operation: getAdjacentUseCases
 */
export async function getAdjacentUseCases(
  request: FastifyRequest<{ Params: { candidateId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: CandidatesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input = {
    candidateId: request.params.candidateId,
  } as GetAdjacentUseCasesInput;
  const result = await deps.useCases.adjacencies.get.execute(input);
  return reply.code(200).send(result);
}


