/**
 * Handlers for Candidate
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: candidates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { CandidatesDomainModule } from "../dependencies/candidates-ddd.dependencies.js";
import type { GetUseCaseCandidateInput, ListUseCaseCandidatesInput, SubmitUseCaseCandidateInput } from "@formulary/services/candidates";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/candidates
 * Operation: listUseCaseCandidates
 */
export async function listUseCaseCandidates(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], stage?: string | string[], quadrant?: string | string[], valueChainStep?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: CandidatesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input = {
    ...(request.query ?? {}),
  } as ListUseCaseCandidatesInput;
  const result = await deps.useCases.candidates.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/candidates
 * Operation: submitUseCaseCandidate
 */
export async function submitUseCaseCandidate(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: CandidatesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input = {
    ...(request.body ?? {}),
  } as SubmitUseCaseCandidateInput;
  const result = await deps.useCases.candidates.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/candidates/{candidateId}
 * Operation: getUseCaseCandidate
 */
export async function getUseCaseCandidate(
  request: FastifyRequest<{ Params: { candidateId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: CandidatesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input = {
    candidateId: request.params.candidateId,
  } as GetUseCaseCandidateInput;
  const result = await deps.useCases.candidates.get.execute(input);
  return reply.code(200).send(result);
}


