/**
 * Candidates DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: candidates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Candidates Domain Module - Composition root
 *
 * DDD: Composition root for candidates domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  AdjacencyRepositoryAdapter,
  CandidateRepositoryAdapter,
  ValuePositionRepositoryAdapter,
} from "@formulary/adapters/candidates";
import { getIdGeneratorService } from "@formulary/adapters";
import type { AdapterDynamoDBClient } from "@formulary/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetAdjacentUseCases,
  ExecuteGetUseCaseCandidate,
  ExecuteListUseCaseCandidates,
  ExecuteSetValuePosition,
  ExecuteSubmitUseCaseCandidate,
} from "@formulary/services/candidates/usecases";
// Ports (interfaces)
import type {
  AdjacencyRepository,
  CandidateRepository,
  ValuePositionRepository,
} from "@formulary/services/candidates/ports";

export interface CandidatesDomainModule {
  repos: {
    adjacencies: AdjacencyRepository;
    candidates: CandidateRepository;
    valuePositions: ValuePositionRepository;
  };
  useCases: {
    candidates: {
      create: ExecuteSubmitUseCaseCandidate;
      get: ExecuteGetUseCaseCandidate;
      list: ExecuteListUseCaseCandidates;
    };
    valuePositions: {
      update: ExecuteSetValuePosition;
    };
    adjacencies: {
      get: ExecuteGetAdjacentUseCases;
    };
  };
}

export function buildCandidatesDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): CandidatesDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      adjacencies?: AdjacencyRepository;
      candidates?: CandidateRepository;
      valuePositions?: ValuePositionRepository;
    } = {};

    obj.adjacencies = new AdjacencyRepositoryAdapter(dynamoClient);
    obj.candidates = new CandidateRepositoryAdapter(dynamoClient);
    obj.valuePositions = new ValuePositionRepositoryAdapter(dynamoClient);
    return {
      adjacencies: obj.adjacencies!,
      candidates: obj.candidates!,
      valuePositions: obj.valuePositions!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    candidates: {
      create: new ExecuteSubmitUseCaseCandidate(executionContext, idGenerator, repos.candidates),
      get: new ExecuteGetUseCaseCandidate(executionContext, idGenerator, repos.candidates),
      list: new ExecuteListUseCaseCandidates(executionContext, idGenerator, repos.candidates),
    },
    valuePositions: {
      update: new ExecuteSetValuePosition(executionContext, idGenerator, repos.valuePositions),
    },
    adjacencies: {
      get: new ExecuteGetAdjacentUseCases(executionContext, idGenerator, repos.adjacencies),
    },
  };
  return { repos, useCases: useCases as CandidatesDomainModule["useCases"] };
}
