/**
 * ExecuteListModelRegistrations - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: registry
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListModelRegistrations Use Case
 *
 * DDD: Application use case for list RegistryModel.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListModelRegistrationsInput, ListModelRegistrationsOutput } from "../dto/registry-model.dto";
import type { ExecutionContextService, IdGeneratorService } from "@formulary/services/_shared/index.js";
import type { RegistryModelRepository } from "../ports";

export class ExecuteListModelRegistrations {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly registryModel: RegistryModelRepository
  ) {}

  async execute(input: ListModelRegistrationsInput): Promise<ListModelRegistrationsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.regId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.registryModel.listModelRegistrations({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListModelRegistrationsOutput;
  }
}
