/**
 * ExecuteListDataDependencies - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: registry
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListDataDependencies Use Case
 *
 * DDD: Application use case for list DataDependency.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListDataDependenciesInput, ListDataDependenciesOutput } from "../dto/data-dependency.dto";
import type { ExecutionContextService, IdGeneratorService } from "@formulary/services/_shared/index.js";
import type { DataDependencyRepository } from "../ports";

export class ExecuteListDataDependencies {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly dataDependency: DataDependencyRepository
  ) {}

  async execute(input: ListDataDependenciesInput): Promise<ListDataDependenciesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.regId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.dataDependency.listDataDependencies({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListDataDependenciesOutput;
  }
}
