/**
 * GetCandidate DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: candidates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetUseCaseCandidateParams } from "@formulary/core/candidates";

export function createGetCandidateRequest(overrides: Partial<GetUseCaseCandidateParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
