/**
 * ExecuteApproveInvestment - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: investment
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteApproveInvestment Use Case
 *
 * DDD: Application use case for create Investment.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ApproveInvestmentInput, ApproveInvestmentOutput } from "../dto/investment.dto";
import type { ExecutionContextService, IdGeneratorService } from "@formulary/services/_shared/index.js";
import type { InvestmentRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteApproveInvestment {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly investment: InvestmentRepository
  ) {}

  async execute(input: ApproveInvestmentInput): Promise<ApproveInvestmentOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.invId();

    // All field names extracted from OpenAPI spec: approvedAmount, approvedBy, decision, expectedBenefit, firstReleaseScope, killCriteria, killDecisionDate
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.killCriteria) {
      throw new ValidationError("killCriteria is required");
    }
    if (!input.killDecisionDate) {
      throw new ValidationError("killDecisionDate is required");
    }
    if (!input.decision) {
      throw new ValidationError("decision is required");
    }
    if (!input.approvedAmount) {
      throw new ValidationError("approvedAmount is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (investment domain)
    const entityId = this.idGenerator.invId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.investment.approveInvestment({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as ApproveInvestmentOutput;
  }
}
