/**
 * ExecuteReviewKillCriteria - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: investment
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteReviewKillCriteria Use Case
 *
 * DDD: Application use case for get KillReview.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ReviewKillCriteriaInput, ReviewKillCriteriaOutput } from "../dto/kill-review.dto";
import type { ExecutionContextService, IdGeneratorService } from "@formulary/services/_shared/index.js";
import type { KillReviewRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteReviewKillCriteria {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly killReview: KillReviewRepository
  ) {}

  async execute(input: ReviewKillCriteriaInput): Promise<ReviewKillCriteriaOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.invId();

    // All field names extracted from OpenAPI spec: metCriteria, outcome, rationale, reviewerId
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).candidateId) {
      throw new ValidationError("candidateId is required");
    }
    const candidateId = (input as any).candidateId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.killReview.reviewKillCriteria({ candidateId: candidateId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${candidateId}`);
    }

    return entity as ReviewKillCriteriaOutput;
  }
}
