/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/benefits/claims": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Claim benefit in insurance financial terms */
        post: operations["claimBenefit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/benefits/claims/{claimId}/close": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                claimId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close benefit with finance confirmation */
        post: operations["closeBenefitWithFinance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Prefixed use-case candidate id */
        CandidateId: string;
        Money: {
            /** Format: double */
            amount: number;
            /** @example EUR */
            currency: string;
        };
        BenefitClaimCreate: {
            /** @description Prefixed use-case candidate id */
            candidateId: string;
            /** @enum {string} */
            benefitKind: "loss_ratio_points" | "expense_ratio_points" | "premium_growth" | "retention_improvement" | "avoided_cost";
            /** Format: float */
            magnitude: number;
            monetaryEquivalent?: {
                /** Format: double */
                amount: number;
                /** @example EUR */
                currency: string;
            };
            lineOfBusiness?: string;
            baselineIsolated?: boolean;
            baselineDescription?: string;
            period: string;
        };
        /** @description RFC 7807 Problem Details (provisional mapping for gateway errors). */
        Problem: {
            /**
             * Format: uri
             * @description URI reference identifying the problem type.
             */
            type?: string;
            /** @description Short human-readable summary. */
            title?: string;
            /** @description HTTP status code. */
            status?: number;
            /** @description Human-readable explanation specific to this occurrence. */
            detail?: string;
            /**
             * Format: uri
             * @description URI reference identifying this occurrence.
             */
            instance?: string;
            /** @description Optional machine-readable error code from the gateway. */
            code?: string;
        } & {
            [key: string]: unknown;
        };
        ClaimId: string;
        BenefitClaim: {
            id?: string;
            /** @description Prefixed use-case candidate id */
            candidateId: string;
            /** @enum {string} */
            benefitKind: "loss_ratio_points" | "expense_ratio_points" | "premium_growth" | "retention_improvement" | "avoided_cost";
            /** Format: float */
            magnitude?: number;
            monetaryEquivalent?: {
                /** Format: double */
                amount: number;
                /** @example EUR */
                currency: string;
            };
            lineOfBusiness?: string;
            /** @description True where increment above existing automation is isolated */
            baselineIsolated?: boolean;
            baselineDescription?: string;
            period?: string;
            claimedBy?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ResponseMeta: {
            /**
             * Format: uuid
             * @description Correlation id for this HTTP request.
             */
            requestId?: string;
            /** @description Optional end-to-end correlation id. */
            correlationId?: string;
            /**
             * Format: date-time
             * @description Server time when the payload was produced.
             */
            generatedAt?: string;
        };
        BenefitClaimResponse: {
            data: {
                id?: string;
                /** @description Prefixed use-case candidate id */
                candidateId: string;
                /** @enum {string} */
                benefitKind: "loss_ratio_points" | "expense_ratio_points" | "premium_growth" | "retention_improvement" | "avoided_cost";
                /** Format: float */
                magnitude?: number;
                monetaryEquivalent?: {
                    /** Format: double */
                    amount: number;
                    /** @example EUR */
                    currency: string;
                };
                lineOfBusiness?: string;
                /** @description True where increment above existing automation is isolated */
                baselineIsolated?: boolean;
                baselineDescription?: string;
                period?: string;
                claimedBy?: string;
                /** Format: date-time */
                createdAt?: string;
                /** Format: date-time */
                updatedAt?: string;
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
        BenefitCloseCreate: {
            /** @enum {string} */
            financeOutcome: "confirmed" | "partially_confirmed" | "denied" | "not_yet_observable";
            /** Format: float */
            confirmedMagnitude?: number;
            confirmedMonetary?: {
                /** Format: double */
                amount: number;
                /** @example EUR */
                currency: string;
            };
            ledgerReference?: string;
            confirmedBy: string;
        };
        BenefitClose: {
            claimId: string;
            /** @enum {string} */
            financeOutcome: "confirmed" | "partially_confirmed" | "denied" | "not_yet_observable";
            /** Format: float */
            confirmedMagnitude?: number;
            confirmedMonetary?: {
                /** Format: double */
                amount: number;
                /** @example EUR */
                currency: string;
            };
            ledgerReference?: string;
            confirmedBy?: string;
            /** Format: float */
            variance?: number;
            /** Format: date-time */
            closedAt?: string;
        };
        BenefitCloseResponse: {
            data: {
                claimId: string;
                /** @enum {string} */
                financeOutcome: "confirmed" | "partially_confirmed" | "denied" | "not_yet_observable";
                /** Format: float */
                confirmedMagnitude?: number;
                confirmedMonetary?: {
                    /** Format: double */
                    amount: number;
                    /** @example EUR */
                    currency: string;
                };
                ledgerReference?: string;
                confirmedBy?: string;
                /** Format: float */
                variance?: number;
                /** Format: date-time */
                closedAt?: string;
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
    };
    responses: {
        /** @description Error (RFC 7807 Problem Details) */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        /** @description Missing or invalid API key */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        /** @description Semantically invalid request (e.g. PACK_EMPTY) */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
    };
    parameters: {
        /**
         * @description Client-supplied key for safe retries on mutating POSTs (≤128 chars).
         *     Replay with the same key and body returns the original result; different
         *     body with the same key yields 409.
         */
        IdempotencyKey: string;
        ClaimId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    claimBenefit: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-supplied key for safe retries on mutating POSTs (≤128 chars).
                 *     Replay with the same key and body returns the original result; different
                 *     body with the same key yields 409.
                 */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Prefixed use-case candidate id */
                    candidateId: string;
                    /** @enum {string} */
                    benefitKind: "loss_ratio_points" | "expense_ratio_points" | "premium_growth" | "retention_improvement" | "avoided_cost";
                    /** Format: float */
                    magnitude: number;
                    monetaryEquivalent?: {
                        /** Format: double */
                        amount: number;
                        /** @example EUR */
                        currency: string;
                    };
                    lineOfBusiness?: string;
                    baselineIsolated?: boolean;
                    baselineDescription?: string;
                    period: string;
                };
            };
        };
        responses: {
            /** @description Benefit claimed in loss-ratio, expense-ratio, or revenue terms */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id?: string;
                            /** @description Prefixed use-case candidate id */
                            candidateId: string;
                            /** @enum {string} */
                            benefitKind: "loss_ratio_points" | "expense_ratio_points" | "premium_growth" | "retention_improvement" | "avoided_cost";
                            /** Format: float */
                            magnitude?: number;
                            monetaryEquivalent?: {
                                /** Format: double */
                                amount: number;
                                /** @example EUR */
                                currency: string;
                            };
                            lineOfBusiness?: string;
                            /** @description True where increment above existing automation is isolated */
                            baselineIsolated?: boolean;
                            baselineDescription?: string;
                            period?: string;
                            claimedBy?: string;
                            /** Format: date-time */
                            createdAt?: string;
                            /** Format: date-time */
                            updatedAt?: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Semantically invalid request (e.g. PACK_EMPTY) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    closeBenefitWithFinance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                claimId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    financeOutcome: "confirmed" | "partially_confirmed" | "denied" | "not_yet_observable";
                    /** Format: float */
                    confirmedMagnitude?: number;
                    confirmedMonetary?: {
                        /** Format: double */
                        amount: number;
                        /** @example EUR */
                        currency: string;
                    };
                    ledgerReference?: string;
                    confirmedBy: string;
                };
            };
        };
        responses: {
            /** @description Finance confirmation or denial of the claimed movement */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            claimId: string;
                            /** @enum {string} */
                            financeOutcome: "confirmed" | "partially_confirmed" | "denied" | "not_yet_observable";
                            /** Format: float */
                            confirmedMagnitude?: number;
                            confirmedMonetary?: {
                                /** Format: double */
                                amount: number;
                                /** @example EUR */
                                currency: string;
                            };
                            ledgerReference?: string;
                            confirmedBy?: string;
                            /** Format: float */
                            variance?: number;
                            /** Format: date-time */
                            closedAt?: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
