/**
 * Repository interface for ValuePosition
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: candidates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  UpdateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  ValuePositionEntity
} from "../models/value-position.entity.js";
import type {
  SetValuePositionRequestInput
} from "../types/index.js";
/**
 * ValuePositionRepository Interface
 */
export interface ValuePositionRepository extends UpdateReadRepository<ValuePositionEntity, SetValuePositionRequestInput, string, Record<string, never>> {

}
