/**
 * ApproveInvestment handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: investment
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { approveInvestment } from "@formulary/api-server/domains/investment/handlers";
import type { InvestmentDDDDependencies } from "@formulary/api-server/domains/investment";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@formulary/tests/shared";
import { INVESTMENT_USE_CASES } from "../__factories__/use-cases.js";

describe("ApproveInvestment", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: InvestmentDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<InvestmentDDDDependencies>(
      INVESTMENT_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeApproveInvestment, "execute").mockResolvedValue(useCaseResult);

    await approveInvestment(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeApproveInvestment.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
