/**
 * Handlers for DataDependency
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: registry
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { RegistryDomainModule } from "../dependencies/registry-ddd.dependencies.js";
import type { ListDataDependenciesInput } from "@formulary/services/registry";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/registry/data-dependencies
 * Operation: listDataDependencies
 */
export async function listDataDependencies(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], dataType?: string | string[], permissionExpiringWithinDays?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: RegistryDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input = {
    ...(request.query ?? {}),
  } as ListDataDependenciesInput;
  const result = await deps.useCases.dataDependencies.list.execute(input);
  return reply.code(200).send(result);
}


