/**
 * Analogue DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: portfolio
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Analogue DTOs
 *
 * DDD: Application DTOs for Analogue use cases.
 */

import type { ListAnalogueCasesParams, RecordAnalogueCaseRequestInput } from "@formulary/core/portfolio/types";

export type ListAnalogueCasesInput = ListAnalogueCasesParams;

export type RecordAnalogueCaseInput = RecordAnalogueCaseRequestInput;

export type ListAnalogueCasesOutput = {};

export type RecordAnalogueCaseOutput = {};
