/**
 * Balance DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: portfolio
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Balance DTOs
 *
 * DDD: Application DTOs for Balance use cases.
 */

import type { GetPortfolioBalanceParams } from "@formulary/core/portfolio/types";

export type GetPortfolioBalanceInput = GetPortfolioBalanceParams;

export type GetPortfolioBalanceOutput = {};
