/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/candidates/{candidateId}/investment": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidateId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve investment with kill criteria */
        post: operations["approveInvestment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/candidates/{candidateId}/kill-review": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidateId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review kill criteria at agreed decision date */
        post: operations["reviewKillCriteria"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Prefixed use-case candidate id */
        CandidateId: string;
        Money: {
            /** Format: double */
            amount: number;
            /** @example EUR */
            currency: string;
        };
        ExpectedBenefit: {
            /** @enum {string} */
            benefitKind: "loss_ratio_points" | "expense_ratio_points" | "premium_growth" | "retention_improvement" | "avoided_cost";
            /** Format: float */
            magnitude: number;
            monetaryEquivalent?: {
                /** Format: double */
                amount: number;
                /** @example EUR */
                currency: string;
            };
            lineOfBusiness?: string;
            baselineIsolated?: boolean;
            baselineDescription?: string;
            period: string;
        };
        KillCriterion: {
            description: string;
            /** @example model precision below 0.6 on holdout claims population */
            measure: string;
            /** Format: float */
            threshold?: number;
            met?: boolean;
        };
        InvestmentDecisionCreate: {
            /** @enum {string} */
            decision: "approved" | "deferred" | "rejected";
            approvedAmount: {
                /** Format: double */
                amount: number;
                /** @example EUR */
                currency: string;
            };
            firstReleaseScope?: string;
            expectedBenefit?: {
                /** @enum {string} */
                benefitKind: "loss_ratio_points" | "expense_ratio_points" | "premium_growth" | "retention_improvement" | "avoided_cost";
                /** Format: float */
                magnitude: number;
                monetaryEquivalent?: {
                    /** Format: double */
                    amount: number;
                    /** @example EUR */
                    currency: string;
                };
                lineOfBusiness?: string;
                baselineIsolated?: boolean;
                baselineDescription?: string;
                period: string;
            };
            killCriteria: {
                description: string;
                /** @example model precision below 0.6 on holdout claims population */
                measure: string;
                /** Format: float */
                threshold?: number;
                met?: boolean;
            }[];
            /** Format: date */
            killDecisionDate: string;
            approvedBy?: string;
        };
        /** @description RFC 7807 Problem Details (provisional mapping for gateway errors). */
        Problem: {
            /**
             * Format: uri
             * @description URI reference identifying the problem type.
             */
            type?: string;
            /** @description Short human-readable summary. */
            title?: string;
            /** @description HTTP status code. */
            status?: number;
            /** @description Human-readable explanation specific to this occurrence. */
            detail?: string;
            /**
             * Format: uri
             * @description URI reference identifying this occurrence.
             */
            instance?: string;
            /** @description Optional machine-readable error code from the gateway. */
            code?: string;
        } & {
            [key: string]: unknown;
        };
        InvestmentDecision: {
            id: string;
            /** @description Prefixed use-case candidate id */
            candidateId: string;
            /** @enum {string} */
            decision: "approved" | "deferred" | "rejected";
            approvedAmount: {
                /** Format: double */
                amount: number;
                /** @example EUR */
                currency: string;
            };
            firstReleaseScope?: string;
            firstReleaseWithinSmallStartLimit?: boolean;
            expectedBenefit?: {
                /** @enum {string} */
                benefitKind: "loss_ratio_points" | "expense_ratio_points" | "premium_growth" | "retention_improvement" | "avoided_cost";
                /** Format: float */
                magnitude: number;
                monetaryEquivalent?: {
                    /** Format: double */
                    amount: number;
                    /** @example EUR */
                    currency: string;
                };
                lineOfBusiness?: string;
                baselineIsolated?: boolean;
                baselineDescription?: string;
                period: string;
            };
            killCriteria?: {
                description: string;
                /** @example model precision below 0.6 on holdout claims population */
                measure: string;
                /** Format: float */
                threshold?: number;
                met?: boolean;
            }[];
            /** Format: date */
            killDecisionDate?: string;
            approvedBy?: string;
            /** Format: date-time */
            decidedAt?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ResponseMeta: {
            /**
             * Format: uuid
             * @description Correlation id for this HTTP request.
             */
            requestId?: string;
            /** @description Optional end-to-end correlation id. */
            correlationId?: string;
            /**
             * Format: date-time
             * @description Server time when the payload was produced.
             */
            generatedAt?: string;
        };
        InvestmentDecisionResponse: {
            data: {
                id: string;
                /** @description Prefixed use-case candidate id */
                candidateId: string;
                /** @enum {string} */
                decision: "approved" | "deferred" | "rejected";
                approvedAmount: {
                    /** Format: double */
                    amount: number;
                    /** @example EUR */
                    currency: string;
                };
                firstReleaseScope?: string;
                firstReleaseWithinSmallStartLimit?: boolean;
                expectedBenefit?: {
                    /** @enum {string} */
                    benefitKind: "loss_ratio_points" | "expense_ratio_points" | "premium_growth" | "retention_improvement" | "avoided_cost";
                    /** Format: float */
                    magnitude: number;
                    monetaryEquivalent?: {
                        /** Format: double */
                        amount: number;
                        /** @example EUR */
                        currency: string;
                    };
                    lineOfBusiness?: string;
                    baselineIsolated?: boolean;
                    baselineDescription?: string;
                    period: string;
                };
                killCriteria?: {
                    description: string;
                    /** @example model precision below 0.6 on holdout claims population */
                    measure: string;
                    /** Format: float */
                    threshold?: number;
                    met?: boolean;
                }[];
                /** Format: date */
                killDecisionDate?: string;
                approvedBy?: string;
                /** Format: date-time */
                decidedAt?: string;
                /** Format: date-time */
                createdAt?: string;
                /** Format: date-time */
                updatedAt?: string;
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
        KillReviewRequest: {
            reviewerId: string;
            /** @enum {string} */
            outcome: "continue" | "kill" | "criteria_not_yet_testable";
            metCriteria?: string[];
            rationale?: string;
        };
        /** @enum {string} */
        ValueChainStep: "product_development" | "marketing_and_sales" | "underwriting_and_risk_rating" | "customer_servicing" | "claims_management" | "financial_assets" | "operations";
        /** @enum {string} */
        CandidateStage: "submitted" | "formula_accepted" | "readiness_assessment" | "conduct_gate" | "awaiting_investment" | "in_delivery" | "live" | "benefit_close" | "killed" | "closed";
        /**
         * @description The x term of the formula
         * @enum {string}
         */
        Functionality: "inform" | "recommend" | "decide";
        /** @enum {string} */
        ModelFamily: "speech_voice_recognition" | "sentiment_detection" | "recommendation_engine" | "text_analytics_nlp" | "pattern_anomaly_detection" | "automatic_decision_management" | "natural_language_generation" | "object_detection" | "biometrics";
        FunctionalitySpec: {
            /**
             * @description The x term of the formula
             * @enum {string}
             */
            functionality: "inform" | "recommend" | "decide";
            description: string;
            modelFamilies?: ("speech_voice_recognition" | "sentiment_detection" | "recommendation_engine" | "text_analytics_nlp" | "pattern_anomaly_detection" | "automatic_decision_management" | "natural_language_generation" | "object_detection" | "biometrics")[];
            humanReviewRequired?: boolean;
        };
        /**
         * @description The y term of the formula
         * @enum {string}
         */
        DataType: "company" | "public" | "third_party" | "customer";
        FormulaDataDependency: {
            id: string;
            /**
             * @description The y term of the formula
             * @enum {string}
             */
            dataType: "company" | "public" | "third_party" | "customer";
            /** @example Motor telematics behavioural feed */
            name: string;
            structured?: boolean;
            /** @enum {string} */
            permissionBasis?: "contractual" | "consent" | "legitimate_interest" | "licensed" | "public_domain" | "not_established";
            onwardTransferTerms?: string;
            /** Format: date */
            permissionRenewalDate?: string;
            /**
             * Format: float
             * @description Share of the in-force book realistically covered
             */
            expectedBookCoverage?: number;
            ownerId?: string;
        };
        NeedStatement: {
            /** @enum {string} */
            audience: "internal_customer" | "external_customer";
            /** @enum {string} */
            needCategory: "product" | "communication" | "operations" | "cost" | "convenience" | "resources";
            /** @description The z term of the formula, stated as a need not a solution */
            statement: string;
        };
        Formula: {
            functionalitySpec: {
                /**
                 * @description The x term of the formula
                 * @enum {string}
                 */
                functionality: "inform" | "recommend" | "decide";
                description: string;
                modelFamilies?: ("speech_voice_recognition" | "sentiment_detection" | "recommendation_engine" | "text_analytics_nlp" | "pattern_anomaly_detection" | "automatic_decision_management" | "natural_language_generation" | "object_detection" | "biometrics")[];
                humanReviewRequired?: boolean;
            };
            dataDependencies: {
                id: string;
                /**
                 * @description The y term of the formula
                 * @enum {string}
                 */
                dataType: "company" | "public" | "third_party" | "customer";
                /** @example Motor telematics behavioural feed */
                name: string;
                structured?: boolean;
                /** @enum {string} */
                permissionBasis?: "contractual" | "consent" | "legitimate_interest" | "licensed" | "public_domain" | "not_established";
                onwardTransferTerms?: string;
                /** Format: date */
                permissionRenewalDate?: string;
                /**
                 * Format: float
                 * @description Share of the in-force book realistically covered
                 */
                expectedBookCoverage?: number;
                ownerId?: string;
            }[];
            need: {
                /** @enum {string} */
                audience: "internal_customer" | "external_customer";
                /** @enum {string} */
                needCategory: "product" | "communication" | "operations" | "cost" | "convenience" | "resources";
                /** @description The z term of the formula, stated as a need not a solution */
                statement: string;
            };
            /** @description Rendered formula sentence for communication */
            statement?: string;
        };
        /**
         * @description Position on the result-type and impact-type axes
         * @enum {string}
         */
        ValueQuadrant: "operations_efficacy" | "customer_efficacy" | "operations_discovery" | "customer_discovery";
        ValuePosition: {
            /** @enum {string} */
            resultType: "known" | "unknown";
            /** @enum {string} */
            impactType: "bottom_line" | "top_line";
            /**
             * @description Position on the result-type and impact-type axes
             * @enum {string}
             */
            quadrant: "operations_efficacy" | "customer_efficacy" | "operations_discovery" | "customer_discovery";
            rationale?: string;
            assignedBy?: string;
        };
        /**
         * @description Declared regulated touchpoints that trigger the conduct gate
         * @enum {string}
         */
        Touchpoint: "rating_factor" | "renewal_price" | "underwriting_acceptance" | "claims_decision" | "fraud_referral" | "reserving_input" | "marketing_targeting" | "none";
        UseCaseCandidate: {
            /** @description Prefixed use-case candidate id */
            id: string;
            title: string;
            sponsorId: string;
            /** @enum {string} */
            valueChainStep?: "product_development" | "marketing_and_sales" | "underwriting_and_risk_rating" | "customer_servicing" | "claims_management" | "financial_assets" | "operations";
            /** @enum {string} */
            stage: "submitted" | "formula_accepted" | "readiness_assessment" | "conduct_gate" | "awaiting_investment" | "in_delivery" | "live" | "benefit_close" | "killed" | "closed";
            formula: {
                functionalitySpec: {
                    /**
                     * @description The x term of the formula
                     * @enum {string}
                     */
                    functionality: "inform" | "recommend" | "decide";
                    description: string;
                    modelFamilies?: ("speech_voice_recognition" | "sentiment_detection" | "recommendation_engine" | "text_analytics_nlp" | "pattern_anomaly_detection" | "automatic_decision_management" | "natural_language_generation" | "object_detection" | "biometrics")[];
                    humanReviewRequired?: boolean;
                };
                dataDependencies: {
                    id: string;
                    /**
                     * @description The y term of the formula
                     * @enum {string}
                     */
                    dataType: "company" | "public" | "third_party" | "customer";
                    /** @example Motor telematics behavioural feed */
                    name: string;
                    structured?: boolean;
                    /** @enum {string} */
                    permissionBasis?: "contractual" | "consent" | "legitimate_interest" | "licensed" | "public_domain" | "not_established";
                    onwardTransferTerms?: string;
                    /** Format: date */
                    permissionRenewalDate?: string;
                    /**
                     * Format: float
                     * @description Share of the in-force book realistically covered
                     */
                    expectedBookCoverage?: number;
                    ownerId?: string;
                }[];
                need: {
                    /** @enum {string} */
                    audience: "internal_customer" | "external_customer";
                    /** @enum {string} */
                    needCategory: "product" | "communication" | "operations" | "cost" | "convenience" | "resources";
                    /** @description The z term of the formula, stated as a need not a solution */
                    statement: string;
                };
                /** @description Rendered formula sentence for communication */
                statement?: string;
            };
            valuePosition?: {
                /** @enum {string} */
                resultType: "known" | "unknown";
                /** @enum {string} */
                impactType: "bottom_line" | "top_line";
                /**
                 * @description Position on the result-type and impact-type axes
                 * @enum {string}
                 */
                quadrant: "operations_efficacy" | "customer_efficacy" | "operations_discovery" | "customer_discovery";
                rationale?: string;
                assignedBy?: string;
            };
            touchpoints?: ("rating_factor" | "renewal_price" | "underwriting_acceptance" | "claims_decision" | "fraud_referral" | "reserving_input" | "marketing_targeting" | "none")[];
            extendsExistingAutomation?: boolean;
            /** @description Existing straight-through baseline the increment sits above */
            baselineReference?: string;
            analogueCaseIds?: string[];
            /** Format: date-time */
            submittedAt?: string;
            /** Format: date */
            killDecisionDate?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        UseCaseCandidateResponse: {
            data: {
                /** @description Prefixed use-case candidate id */
                id: string;
                title: string;
                sponsorId: string;
                /** @enum {string} */
                valueChainStep?: "product_development" | "marketing_and_sales" | "underwriting_and_risk_rating" | "customer_servicing" | "claims_management" | "financial_assets" | "operations";
                /** @enum {string} */
                stage: "submitted" | "formula_accepted" | "readiness_assessment" | "conduct_gate" | "awaiting_investment" | "in_delivery" | "live" | "benefit_close" | "killed" | "closed";
                formula: {
                    functionalitySpec: {
                        /**
                         * @description The x term of the formula
                         * @enum {string}
                         */
                        functionality: "inform" | "recommend" | "decide";
                        description: string;
                        modelFamilies?: ("speech_voice_recognition" | "sentiment_detection" | "recommendation_engine" | "text_analytics_nlp" | "pattern_anomaly_detection" | "automatic_decision_management" | "natural_language_generation" | "object_detection" | "biometrics")[];
                        humanReviewRequired?: boolean;
                    };
                    dataDependencies: {
                        id: string;
                        /**
                         * @description The y term of the formula
                         * @enum {string}
                         */
                        dataType: "company" | "public" | "third_party" | "customer";
                        /** @example Motor telematics behavioural feed */
                        name: string;
                        structured?: boolean;
                        /** @enum {string} */
                        permissionBasis?: "contractual" | "consent" | "legitimate_interest" | "licensed" | "public_domain" | "not_established";
                        onwardTransferTerms?: string;
                        /** Format: date */
                        permissionRenewalDate?: string;
                        /**
                         * Format: float
                         * @description Share of the in-force book realistically covered
                         */
                        expectedBookCoverage?: number;
                        ownerId?: string;
                    }[];
                    need: {
                        /** @enum {string} */
                        audience: "internal_customer" | "external_customer";
                        /** @enum {string} */
                        needCategory: "product" | "communication" | "operations" | "cost" | "convenience" | "resources";
                        /** @description The z term of the formula, stated as a need not a solution */
                        statement: string;
                    };
                    /** @description Rendered formula sentence for communication */
                    statement?: string;
                };
                valuePosition?: {
                    /** @enum {string} */
                    resultType: "known" | "unknown";
                    /** @enum {string} */
                    impactType: "bottom_line" | "top_line";
                    /**
                     * @description Position on the result-type and impact-type axes
                     * @enum {string}
                     */
                    quadrant: "operations_efficacy" | "customer_efficacy" | "operations_discovery" | "customer_discovery";
                    rationale?: string;
                    assignedBy?: string;
                };
                touchpoints?: ("rating_factor" | "renewal_price" | "underwriting_acceptance" | "claims_decision" | "fraud_referral" | "reserving_input" | "marketing_targeting" | "none")[];
                extendsExistingAutomation?: boolean;
                /** @description Existing straight-through baseline the increment sits above */
                baselineReference?: string;
                analogueCaseIds?: string[];
                /** Format: date-time */
                submittedAt?: string;
                /** Format: date */
                killDecisionDate?: string;
                /** Format: date-time */
                createdAt?: string;
                /** Format: date-time */
                updatedAt?: string;
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
    };
    responses: {
        /** @description Error (RFC 7807 Problem Details) */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        /** @description Missing or invalid API key */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        /** @description Idempotency key reuse with different body, or state conflict */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        /** @description Semantically invalid request (e.g. PACK_EMPTY) */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
    };
    parameters: {
        CandidateId: string;
        /**
         * @description Client-supplied key for safe retries on mutating POSTs (≤128 chars).
         *     Replay with the same key and body returns the original result; different
         *     body with the same key yields 409.
         */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    approveInvestment: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-supplied key for safe retries on mutating POSTs (≤128 chars).
                 *     Replay with the same key and body returns the original result; different
                 *     body with the same key yields 409.
                 */
                "Idempotency-Key": string;
            };
            path: {
                candidateId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    decision: "approved" | "deferred" | "rejected";
                    approvedAmount: {
                        /** Format: double */
                        amount: number;
                        /** @example EUR */
                        currency: string;
                    };
                    firstReleaseScope?: string;
                    expectedBenefit?: {
                        /** @enum {string} */
                        benefitKind: "loss_ratio_points" | "expense_ratio_points" | "premium_growth" | "retention_improvement" | "avoided_cost";
                        /** Format: float */
                        magnitude: number;
                        monetaryEquivalent?: {
                            /** Format: double */
                            amount: number;
                            /** @example EUR */
                            currency: string;
                        };
                        lineOfBusiness?: string;
                        baselineIsolated?: boolean;
                        baselineDescription?: string;
                        period: string;
                    };
                    killCriteria: {
                        description: string;
                        /** @example model precision below 0.6 on holdout claims population */
                        measure: string;
                        /** Format: float */
                        threshold?: number;
                        met?: boolean;
                    }[];
                    /** Format: date */
                    killDecisionDate: string;
                    approvedBy?: string;
                };
            };
        };
        responses: {
            /** @description Investment approved with first-release scope and kill criteria */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            /** @description Prefixed use-case candidate id */
                            candidateId: string;
                            /** @enum {string} */
                            decision: "approved" | "deferred" | "rejected";
                            approvedAmount: {
                                /** Format: double */
                                amount: number;
                                /** @example EUR */
                                currency: string;
                            };
                            firstReleaseScope?: string;
                            firstReleaseWithinSmallStartLimit?: boolean;
                            expectedBenefit?: {
                                /** @enum {string} */
                                benefitKind: "loss_ratio_points" | "expense_ratio_points" | "premium_growth" | "retention_improvement" | "avoided_cost";
                                /** Format: float */
                                magnitude: number;
                                monetaryEquivalent?: {
                                    /** Format: double */
                                    amount: number;
                                    /** @example EUR */
                                    currency: string;
                                };
                                lineOfBusiness?: string;
                                baselineIsolated?: boolean;
                                baselineDescription?: string;
                                period: string;
                            };
                            killCriteria?: {
                                description: string;
                                /** @example model precision below 0.6 on holdout claims population */
                                measure: string;
                                /** Format: float */
                                threshold?: number;
                                met?: boolean;
                            }[];
                            /** Format: date */
                            killDecisionDate?: string;
                            approvedBy?: string;
                            /** Format: date-time */
                            decidedAt?: string;
                            /** Format: date-time */
                            createdAt?: string;
                            /** Format: date-time */
                            updatedAt?: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Idempotency key reuse with different body, or state conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    reviewKillCriteria: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidateId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    reviewerId: string;
                    /** @enum {string} */
                    outcome: "continue" | "kill" | "criteria_not_yet_testable";
                    metCriteria?: string[];
                    rationale?: string;
                };
            };
        };
        responses: {
            /** @description Kill decision at the agreed decision date */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            /** @description Prefixed use-case candidate id */
                            id: string;
                            title: string;
                            sponsorId: string;
                            /** @enum {string} */
                            valueChainStep?: "product_development" | "marketing_and_sales" | "underwriting_and_risk_rating" | "customer_servicing" | "claims_management" | "financial_assets" | "operations";
                            /** @enum {string} */
                            stage: "submitted" | "formula_accepted" | "readiness_assessment" | "conduct_gate" | "awaiting_investment" | "in_delivery" | "live" | "benefit_close" | "killed" | "closed";
                            formula: {
                                functionalitySpec: {
                                    /**
                                     * @description The x term of the formula
                                     * @enum {string}
                                     */
                                    functionality: "inform" | "recommend" | "decide";
                                    description: string;
                                    modelFamilies?: ("speech_voice_recognition" | "sentiment_detection" | "recommendation_engine" | "text_analytics_nlp" | "pattern_anomaly_detection" | "automatic_decision_management" | "natural_language_generation" | "object_detection" | "biometrics")[];
                                    humanReviewRequired?: boolean;
                                };
                                dataDependencies: {
                                    id: string;
                                    /**
                                     * @description The y term of the formula
                                     * @enum {string}
                                     */
                                    dataType: "company" | "public" | "third_party" | "customer";
                                    /** @example Motor telematics behavioural feed */
                                    name: string;
                                    structured?: boolean;
                                    /** @enum {string} */
                                    permissionBasis?: "contractual" | "consent" | "legitimate_interest" | "licensed" | "public_domain" | "not_established";
                                    onwardTransferTerms?: string;
                                    /** Format: date */
                                    permissionRenewalDate?: string;
                                    /**
                                     * Format: float
                                     * @description Share of the in-force book realistically covered
                                     */
                                    expectedBookCoverage?: number;
                                    ownerId?: string;
                                }[];
                                need: {
                                    /** @enum {string} */
                                    audience: "internal_customer" | "external_customer";
                                    /** @enum {string} */
                                    needCategory: "product" | "communication" | "operations" | "cost" | "convenience" | "resources";
                                    /** @description The z term of the formula, stated as a need not a solution */
                                    statement: string;
                                };
                                /** @description Rendered formula sentence for communication */
                                statement?: string;
                            };
                            valuePosition?: {
                                /** @enum {string} */
                                resultType: "known" | "unknown";
                                /** @enum {string} */
                                impactType: "bottom_line" | "top_line";
                                /**
                                 * @description Position on the result-type and impact-type axes
                                 * @enum {string}
                                 */
                                quadrant: "operations_efficacy" | "customer_efficacy" | "operations_discovery" | "customer_discovery";
                                rationale?: string;
                                assignedBy?: string;
                            };
                            touchpoints?: ("rating_factor" | "renewal_price" | "underwriting_acceptance" | "claims_decision" | "fraud_referral" | "reserving_input" | "marketing_targeting" | "none")[];
                            extendsExistingAutomation?: boolean;
                            /** @description Existing straight-through baseline the increment sits above */
                            baselineReference?: string;
                            analogueCaseIds?: string[];
                            /** Format: date-time */
                            submittedAt?: string;
                            /** Format: date */
                            killDecisionDate?: string;
                            /** Format: date-time */
                            createdAt?: string;
                            /** Format: date-time */
                            updatedAt?: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Semantically invalid request (e.g. PACK_EMPTY) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
