/**
 * Readiness DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: readiness
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Readiness Domain Module - Composition root
 *
 * DDD: Composition root for readiness domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  DataBlockerRepositoryAdapter,
  ReadinessRepositoryAdapter,
} from "@formulary/adapters/readiness";
import { getIdGeneratorService } from "@formulary/adapters";
import type { AdapterDynamoDBClient } from "@formulary/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetDataReadinessVerdict,
  ExecuteIssueDataReadinessVerdict,
  ExecuteListDataBlockers,
} from "@formulary/services/readiness/usecases";
// Ports (interfaces)
import type {
  DataBlockerRepository,
  ReadinessRepository,
} from "@formulary/services/readiness/ports";

export interface ReadinessDomainModule {
  repos: {
    dataBlockers: DataBlockerRepository;
    readinesses: ReadinessRepository;
  };
  useCases: {
    dataBlockers: {
      list: ExecuteListDataBlockers;
    };
    readinesses: {
      get: ExecuteGetDataReadinessVerdict;
    };
  };
}

export function buildReadinessDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): ReadinessDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      dataBlockers?: DataBlockerRepository;
      readinesses?: ReadinessRepository;
    } = {};

    obj.dataBlockers = new DataBlockerRepositoryAdapter(dynamoClient);
    obj.readinesses = new ReadinessRepositoryAdapter(dynamoClient);
    return {
      dataBlockers: obj.dataBlockers!,
      readinesses: obj.readinesses!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    dataBlockers: {
      list: new ExecuteListDataBlockers(executionContext, idGenerator, repos.dataBlockers),
    },
    readinesses: {
      get: new ExecuteGetDataReadinessVerdict(executionContext, idGenerator, repos.readinesses),
    },
  };
  return { repos, useCases: useCases as ReadinessDomainModule["useCases"] };
}
