/**
 * InvestmentRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: investment
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * InvestmentRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements InvestmentRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  InvestmentRepository,
} from "@formulary/services/investment";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { InvestmentRepositoryDdb } from "./investment-repository.ddb.js";

/**
 * InvestmentRepositoryAdapter
 *
 * Implements InvestmentRepository port for infrastructure layer.
 */
export class InvestmentRepositoryAdapter implements InvestmentRepository {
  private readonly ddb: InvestmentRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new InvestmentRepositoryDdb(this.dynamoClient);
  }

  async approveInvestment(input: Parameters<InvestmentRepository['approveInvestment']>[0]): Promise<Awaited<ReturnType<InvestmentRepository['approveInvestment']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.approveInvestment(input);
  }
}
