/**
 * KillReviewRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: investment
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * KillReviewRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements KillReviewRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  KillReviewRepository,
} from "@formulary/services/investment";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { KillReviewRepositoryDdb } from "./kill-review-repository.ddb.js";

/**
 * KillReviewRepositoryAdapter
 *
 * Implements KillReviewRepository port for infrastructure layer.
 */
export class KillReviewRepositoryAdapter implements KillReviewRepository {
  private readonly ddb: KillReviewRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new KillReviewRepositoryDdb(this.dynamoClient);
  }

  async reviewKillCriteria(input: Parameters<KillReviewRepository['reviewKillCriteria']>[0]): Promise<Awaited<ReturnType<KillReviewRepository['reviewKillCriteria']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.reviewKillCriteria(input);
  }
}
