/**
 * Routes for Adjacency
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: candidates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getAdjacentUseCases } from "../handlers/adjacency.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function adjacencyRoutes(fastify: FastifyInstance) {
  // GET /v1/candidates/{candidateId}/adjacency (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/candidates/:candidateId/adjacency",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { candidateId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getCandidatesDependenciesForRequest();
        await getAdjacentUseCases(request, reply, deps);
      });
    }
  );


}
