/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: candidates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { adjacencyRoutes } from "./adjacency.routes.js";
export { candidateRoutes } from "./candidate.routes.js";
export { valuePositionRoutes } from "./value-position.routes.js";
