/**
 * Routes for ValuePosition
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: candidates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { setValuePosition } from "../handlers/value-position.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function valuePositionRoutes(fastify: FastifyInstance) {
  // PUT /v1/candidates/{candidateId}/value-position (unscoped; scope set for security middleware)
  fastify.put(
    "/v1/candidates/:candidateId/value-position",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { candidateId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getCandidatesDependenciesForRequest();
        await setValuePosition(request, reply, deps);
      });
    }
  );


}
