/**
 * BalanceRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: portfolio
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * BalanceRepository Port
 *
 * DDD: Application port for balancerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetPortfolioBalanceInput, GetPortfolioBalanceOutput } from "../dto/balance.dto";
export interface BalanceRepository {
  getPortfolioBalance(input: GetPortfolioBalanceInput): Promise<GetPortfolioBalanceOutput>;
}

export type { GetPortfolioBalanceInput, GetPortfolioBalanceOutput } from "../dto/balance.dto";
