/**
 * ReadinessRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: readiness
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ReadinessRepository Port
 *
 * DDD: Application port for readinessrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetDataReadinessVerdictInput, GetDataReadinessVerdictOutput, IssueDataReadinessVerdictInput, IssueDataReadinessVerdictOutput } from "../dto/readiness.dto";
export interface ReadinessRepository {
  issueDataReadinessVerdict(input: IssueDataReadinessVerdictInput): Promise<IssueDataReadinessVerdictOutput>;
  getDataReadinessVerdict(input: GetDataReadinessVerdictInput): Promise<GetDataReadinessVerdictOutput>;
}

export type { GetDataReadinessVerdictInput, GetDataReadinessVerdictOutput, IssueDataReadinessVerdictInput, IssueDataReadinessVerdictOutput } from "../dto/readiness.dto";
