/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: portfolio
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Portfolio Domain Use Cases
 * 
 * List of all use case names for the portfolio domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const PORTFOLIO_USE_CASES = [
  "executeGetCommitteePack",
  "executeGetPortfolioBalance",
  "executeListAnalogueCases",
  "executeRecordAnalogueCase"
] as const;
