/**
 * Repository interface for DataBlocker
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: readiness
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  ReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  DataBlockerEntity
} from "../models/data-blocker.entity.js";
import type {
  ListDataBlockersParams
} from "../types/index.js";
/**
 * DataBlockerRepository Interface
 */
export interface DataBlockerRepository extends ReadRepository<DataBlockerEntity, string, ListDataBlockersParams> {

}
