/**
 * Adjacency DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: candidates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Adjacency DTOs
 *
 * DDD: Application DTOs for Adjacency use cases.
 */

import type { GetAdjacentUseCasesParams } from "@formulary/core/candidates/types";

export type GetAdjacentUseCasesInput = GetAdjacentUseCasesParams;

export type GetAdjacentUseCasesOutput = {};
