/**
 * Candidate DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: candidates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Candidate DTOs
 *
 * DDD: Application DTOs for Candidate use cases.
 */

import type { GetUseCaseCandidateParams, ListUseCaseCandidatesParams, SubmitUseCaseCandidateRequestInput } from "@formulary/core/candidates/types";

export type ListUseCaseCandidatesInput = ListUseCaseCandidatesParams;

export type SubmitUseCaseCandidateInput = SubmitUseCaseCandidateRequestInput;

export type GetUseCaseCandidateInput = GetUseCaseCandidateParams;

export type ListUseCaseCandidatesOutput = {};

export type SubmitUseCaseCandidateOutput = {};

export type GetUseCaseCandidateOutput = {};
