/**
 * ValuePosition DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: candidates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ValuePosition DTOs
 *
 * DDD: Application DTOs for ValuePosition use cases.
 */

import type { SetValuePositionParams, SetValuePositionRequestInput } from "@formulary/core/candidates/types";

export type SetValuePositionInput = SetValuePositionParams & SetValuePositionRequestInput;

export type SetValuePositionOutput = {};
