/**
 * DataDependencyRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: registry
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DataDependencyRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements DataDependencyRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  DataDependencyRepository,
} from "@formulary/services/registry";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { DataDependencyRepositoryDdb } from "./data-dependency-repository.ddb.js";

/**
 * DataDependencyRepositoryAdapter
 *
 * Implements DataDependencyRepository port for infrastructure layer.
 */
export class DataDependencyRepositoryAdapter implements DataDependencyRepository {
  private readonly ddb: DataDependencyRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new DataDependencyRepositoryDdb(this.dynamoClient);
  }

  async listDataDependencies(input: Parameters<DataDependencyRepository['listDataDependencies']>[0]): Promise<Awaited<ReturnType<DataDependencyRepository['listDataDependencies']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listDataDependencies(input);
  }
}
