/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: registry
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./data-dependency-repository.ddb.js";
export * from "./registry-model-repository.ddb.js";
export * from "./data-dependency-repository.adapter.js";
export * from "./registry-model-repository.adapter.js";
