/**
 * RegistryModelRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: registry
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RegistryModelRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements RegistryModelRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  RegistryModelRepository,
} from "@formulary/services/registry";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { RegistryModelRepositoryDdb } from "./registry-model-repository.ddb.js";

/**
 * RegistryModelRepositoryAdapter
 *
 * Implements RegistryModelRepository port for infrastructure layer.
 */
export class RegistryModelRepositoryAdapter implements RegistryModelRepository {
  private readonly ddb: RegistryModelRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new RegistryModelRepositoryDdb(this.dynamoClient);
  }

  async listModelRegistrations(input: Parameters<RegistryModelRepository['listModelRegistrations']>[0]): Promise<Awaited<ReturnType<RegistryModelRepository['listModelRegistrations']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listModelRegistrations(input);
  }

  async registerModel(input: Parameters<RegistryModelRepository['registerModel']>[0]): Promise<Awaited<ReturnType<RegistryModelRepository['registerModel']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.registerModel(input);
  }
}
