/**
 * Main Services Package Index
 *
 * Generated by Services Main Index Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: candidates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Services Package - Main Barrel Export
 *
 * Central export point for all application services (use cases, ports, DTOs, policies, errors)
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended)
 *   import { activity, ai, conversation } from "@formulary/services";
 *   const { usecases, dto, ports } = activity;
 *
 *   // Direct imports from domain
 *   import { ExecuteCreateEventUseCase } from "@formulary/services/activity";
 *   
 *   // Shared services
 *   import { executionContextService } from "@formulary/services";
 */

// ============================================================================
// SHARED SERVICES EXPORTS
// ============================================================================
export { executionContextService } from "./_shared/index.js";

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types across domains

import * as _benefits from "./benefits/index.js";
import * as _candidates from "./candidates/index.js";
import * as _gates from "./gates/index.js";
import * as _identity from "./identity/index.js";
import * as _investment from "./investment/index.js";
import * as _portfolio from "./portfolio/index.js";
import * as _readiness from "./readiness/index.js";
import * as _registry from "./registry/index.js";

// Export as namespaces
export const benefits = _benefits;
export const candidates = _candidates;
export const gates = _gates;
export const identity = _identity;
export const investment = _investment;
export const portfolio = _portfolio;
export const readiness = _readiness;
export const registry = _registry;
