/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: readiness
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Readiness Domain Use Cases
 * 
 * List of all use case names for the readiness domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const READINESS_USE_CASES = [
  "executeGetDataReadinessVerdict",
  "executeIssueDataReadinessVerdict",
  "executeListDataBlockers"
] as const;
