/**
 * FeatureRiskFinding Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { FeatureRiskFindingEntity } from "@formulary/core/gates/models/index.js";
import { gatesSchemas } from "@formulary/core/gates";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "gate";

export function createFeatureRiskFinding(overrides: Partial<FeatureRiskFindingEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    feature: overrides.feature ?? faker.lorem.word(),
    riskType: overrides.riskType ?? "proxy_for_protected_characteristic",
    ...overrides,
  };

  return gatesSchemas.FeatureRiskFinding.parse(raw);
}

export function featureRiskFindingBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createFeatureRiskFinding(overrides));
}
