/**
 * RaiseFeatureRiskFinding handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { raiseFeatureRiskFinding } from "@formulary/api-server/domains/gates/handlers";
import type { GatesDDDDependencies } from "@formulary/api-server/domains/gates";
import { createFeatureRiskFinding as createFeatureRiskFindingEntity } from "@formulary/factories/gates";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@formulary/tests/shared";
import { GATES_USE_CASES } from "../__factories__/use-cases.js";

describe("RaiseFeatureRiskFinding", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: GatesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<GatesDDDDependencies>(
      GATES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createFeatureRiskFindingEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeRaiseFeatureRiskFinding, "execute").mockResolvedValue(useCaseResult);

    await raiseFeatureRiskFinding(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeRaiseFeatureRiskFinding.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
