/**
 * ConductGateRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ConductGateRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ConductGateRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ConductGateRepository,
} from "@formulary/services/gates";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ConductGateRepositoryDdb } from "./conduct-gate-repository.ddb.js";

/**
 * ConductGateRepositoryAdapter
 *
 * Implements ConductGateRepository port for infrastructure layer.
 */
export class ConductGateRepositoryAdapter implements ConductGateRepository {
  private readonly ddb: ConductGateRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ConductGateRepositoryDdb(this.dynamoClient);
  }

  async openConductGateReview(input: Parameters<ConductGateRepository['openConductGateReview']>[0]): Promise<Awaited<ReturnType<ConductGateRepository['openConductGateReview']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.openConductGateReview(input);
  }
}
