/**
 * DecisionRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DecisionRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements DecisionRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  DecisionRepository,
} from "@formulary/services/gates";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { DecisionRepositoryDdb } from "./decision-repository.ddb.js";

/**
 * DecisionRepositoryAdapter
 *
 * Implements DecisionRepository port for infrastructure layer.
 */
export class DecisionRepositoryAdapter implements DecisionRepository {
  private readonly ddb: DecisionRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new DecisionRepositoryDdb(this.dynamoClient);
  }

  async decideConductGate(input: Parameters<DecisionRepository['decideConductGate']>[0]): Promise<Awaited<ReturnType<DecisionRepository['decideConductGate']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.decideConductGate(input);
  }
}
