/**
 * Gates DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Gates Domain Module - Composition root
 *
 * DDD: Composition root for gates domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  ConductGateRepositoryAdapter,
  DecisionRepositoryAdapter,
  FeatureRiskFindingRepositoryAdapter,
} from "@formulary/adapters/gates";
import { getIdGeneratorService } from "@formulary/adapters";
import type { AdapterDynamoDBClient } from "@formulary/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteDecideConductGate,
  ExecuteOpenConductGateReview,
  ExecuteRaiseFeatureRiskFinding,
} from "@formulary/services/gates/usecases";
// Ports (interfaces)
import type {
  ConductGateRepository,
  DecisionRepository,
  FeatureRiskFindingRepository,
} from "@formulary/services/gates/ports";

export interface GatesDomainModule {
  repos: {
    conductGates: ConductGateRepository;
    decisions: DecisionRepository;
    featureRiskFindings: FeatureRiskFindingRepository;
  };
  useCases: {
    conductGates: {
      get: ExecuteOpenConductGateReview;
    };
    decisions: {
      get: ExecuteDecideConductGate;
    };
    featureRiskFindings: {
      get: ExecuteRaiseFeatureRiskFinding;
    };
  };
}

export function buildGatesDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): GatesDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      conductGates?: ConductGateRepository;
      decisions?: DecisionRepository;
      featureRiskFindings?: FeatureRiskFindingRepository;
    } = {};

    obj.conductGates = new ConductGateRepositoryAdapter(dynamoClient);
    obj.decisions = new DecisionRepositoryAdapter(dynamoClient);
    obj.featureRiskFindings = new FeatureRiskFindingRepositoryAdapter(dynamoClient);
    return {
      conductGates: obj.conductGates!,
      decisions: obj.decisions!,
      featureRiskFindings: obj.featureRiskFindings!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    conductGates: {
      get: new ExecuteOpenConductGateReview(executionContext, idGenerator, repos.conductGates),
    },
    decisions: {
      get: new ExecuteDecideConductGate(executionContext, idGenerator, repos.decisions),
    },
    featureRiskFindings: {
      get: new ExecuteRaiseFeatureRiskFinding(executionContext, idGenerator, repos.featureRiskFindings),
    },
  };
  return { repos, useCases: useCases as GatesDomainModule["useCases"] };
}
