/**
 * ExecuteListAnalogueCases - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: portfolio
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListAnalogueCases Use Case
 *
 * DDD: Application use case for list Analogue.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListAnalogueCasesInput, ListAnalogueCasesOutput } from "../dto/analogue.dto";
import type { ExecutionContextService, IdGeneratorService } from "@formulary/services/_shared/index.js";
import type { AnalogueRepository } from "../ports";

export class ExecuteListAnalogueCases {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly analogue: AnalogueRepository
  ) {}

  async execute(input: ListAnalogueCasesInput): Promise<ListAnalogueCasesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.ptfId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.analogue.listAnalogueCases({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListAnalogueCasesOutput;
  }
}
