/**
 * AdjacencyRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: candidates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AdjacencyRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements AdjacencyRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  AdjacencyRepository,
} from "@formulary/services/candidates";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { AdjacencyRepositoryDdb } from "./adjacency-repository.ddb.js";

/**
 * AdjacencyRepositoryAdapter
 *
 * Implements AdjacencyRepository port for infrastructure layer.
 */
export class AdjacencyRepositoryAdapter implements AdjacencyRepository {
  private readonly ddb: AdjacencyRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new AdjacencyRepositoryDdb(this.dynamoClient);
  }

  async getAdjacentUseCases(input: Parameters<AdjacencyRepository['getAdjacentUseCases']>[0]): Promise<Awaited<ReturnType<AdjacencyRepository['getAdjacentUseCases']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getAdjacentUseCases(input);
  }
}
