/**
 * ValuePositionRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: candidates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ValuePositionRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ValuePositionRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ValuePositionRepository,
} from "@formulary/services/candidates";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ValuePositionRepositoryDdb } from "./value-position-repository.ddb.js";

/**
 * ValuePositionRepositoryAdapter
 *
 * Implements ValuePositionRepository port for infrastructure layer.
 */
export class ValuePositionRepositoryAdapter implements ValuePositionRepository {
  private readonly ddb: ValuePositionRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ValuePositionRepositoryDdb(this.dynamoClient);
  }

  async setValuePosition(input: Parameters<ValuePositionRepository['setValuePosition']>[0]): Promise<Awaited<ReturnType<ValuePositionRepository['setValuePosition']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.setValuePosition(input);
  }
}
