/**
 * ConductGateRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ConductGateRepository Port
 *
 * DDD: Application port for conductgaterepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { OpenConductGateReviewInput, OpenConductGateReviewOutput } from "../dto/conduct-gate.dto";
export interface ConductGateRepository {
  openConductGateReview(input: OpenConductGateReviewInput): Promise<OpenConductGateReviewOutput>;
}

export type { OpenConductGateReviewInput, OpenConductGateReviewOutput } from "../dto/conduct-gate.dto";
