/**
 * FeatureRiskFindingRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * FeatureRiskFindingRepository Port
 *
 * DDD: Application port for featureriskfindingrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { RaiseFeatureRiskFindingInput, RaiseFeatureRiskFindingOutput } from "../dto/feature-risk-finding.dto";
export interface FeatureRiskFindingRepository {
  raiseFeatureRiskFinding(input: RaiseFeatureRiskFindingInput): Promise<RaiseFeatureRiskFindingOutput>;
}

export type { RaiseFeatureRiskFindingInput, RaiseFeatureRiskFindingOutput } from "../dto/feature-risk-finding.dto";
