/**
 * Investment DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: investment
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Investment Domain Module - Composition root
 *
 * DDD: Composition root for investment domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  InvestmentRepositoryAdapter,
  KillReviewRepositoryAdapter,
} from "@formulary/adapters/investment";
import { getIdGeneratorService } from "@formulary/adapters";
import type { AdapterDynamoDBClient } from "@formulary/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteApproveInvestment,
  ExecuteReviewKillCriteria,
} from "@formulary/services/investment/usecases";
// Ports (interfaces)
import type {
  InvestmentRepository,
  KillReviewRepository,
} from "@formulary/services/investment/ports";

export interface InvestmentDomainModule {
  repos: {
    investments: InvestmentRepository;
    killReviews: KillReviewRepository;
  };
  useCases: {
    investments: {
      create: ExecuteApproveInvestment;
    };
    killReviews: {
      get: ExecuteReviewKillCriteria;
    };
  };
}

export function buildInvestmentDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): InvestmentDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      investments?: InvestmentRepository;
      killReviews?: KillReviewRepository;
    } = {};

    obj.investments = new InvestmentRepositoryAdapter(dynamoClient);
    obj.killReviews = new KillReviewRepositoryAdapter(dynamoClient);
    return {
      investments: obj.investments!,
      killReviews: obj.killReviews!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    investments: {
      create: new ExecuteApproveInvestment(executionContext, idGenerator, repos.investments),
    },
    killReviews: {
      get: new ExecuteReviewKillCriteria(executionContext, idGenerator, repos.killReviews),
    },
  };
  return { repos, useCases: useCases as InvestmentDomainModule["useCases"] };
}
