/**
 * Handlers for ConductGate
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { GatesDomainModule } from "../dependencies/gates-ddd.dependencies.js";
import type { OpenConductGateReviewInput } from "@formulary/services/gates";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/candidates/{candidateId}/conduct-gate
 * Operation: openConductGateReview
 */
export async function openConductGateReview(
  request: FastifyRequest<{ Params: { candidateId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: GatesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input = {
    candidateId: request.params.candidateId,
    ...(request.body ?? {}),
  } as OpenConductGateReviewInput;
  const result = await deps.useCases.conductGates.get.execute(input);
  return reply.code(201).send(result);
}


