/**
 * Handlers for FeatureRiskFinding
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { GatesDomainModule } from "../dependencies/gates-ddd.dependencies.js";
import type { RaiseFeatureRiskFindingInput } from "@formulary/services/gates";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/conduct-gate-reviews/{reviewId}/feature-risk-findings
 * Operation: raiseFeatureRiskFinding
 */
export async function raiseFeatureRiskFinding(
  request: FastifyRequest<{ Params: { reviewId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: GatesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input = {
    reviewId: request.params.reviewId,
    ...(request.body ?? {}),
  } as RaiseFeatureRiskFindingInput;
  const result = await deps.useCases.featureRiskFindings.get.execute(input);
  return reply.code(201).send(result);
}


