/**
 * DataDependency DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: registry
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DataDependency DTOs
 *
 * DDD: Application DTOs for DataDependency use cases.
 */

import type { ListDataDependenciesParams } from "@formulary/core/registry/types";

export type ListDataDependenciesInput = ListDataDependenciesParams;

export type ListDataDependenciesOutput = {};
