/**
 * ClaimRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: benefits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ClaimRepository Port
 *
 * DDD: Application port for claimrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ClaimBenefitInput, ClaimBenefitOutput } from "../dto/claim.dto";
export interface ClaimRepository {
  claimBenefit(input: ClaimBenefitInput): Promise<ClaimBenefitOutput>;
}

export type { ClaimBenefitInput, ClaimBenefitOutput } from "../dto/claim.dto";
