/**
 * Handlers for ApiKey
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: identity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { IdentityDomainModule } from "../dependencies/identity-ddd.dependencies.js";
import type { CreateTenantApiKeyInput, GetTenantApiKeyInput, ListTenantApiKeysInput, RevokeTenantApiKeyInput } from "@formulary/services/identity";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v0/tenants/me/api-keys
 * Operation: listTenantApiKeys
 */
export async function listTenantApiKeys(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: IdentityDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListTenantApiKeysInput = {};
  const result = await deps.useCases.apiKeys.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v0/tenants/me/api-keys
 * Operation: createTenantApiKey
 */
export async function createTenantApiKey(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: IdentityDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input = {
    ...(request.body ?? {}),
  } as CreateTenantApiKeyInput;
  const result = await deps.useCases.apiKeys.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v0/tenants/me/api-keys/{keyId}
 * Operation: getTenantApiKey
 */
export async function getTenantApiKey(
  request: FastifyRequest<{ Params: { keyId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: IdentityDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input = {
    keyId: request.params.keyId,
  } as GetTenantApiKeyInput;
  const result = await deps.useCases.apiKeys.get.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for DELETE /v0/tenants/me/api-keys/{keyId}
 * Operation: revokeTenantApiKey
 */
export async function revokeTenantApiKey(
  request: FastifyRequest<{ Params: { keyId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: IdentityDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input = {
    keyId: request.params.keyId,
  } as RevokeTenantApiKeyInput;
  const result = await deps.useCases.apiKeys.revoke.execute(input);
  return reply.code(204).send(result);
}


