/**
 * Decision DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Decision DTOs
 *
 * DDD: Application DTOs for Decision use cases.
 */

import type { DecideConductGateParams, DecideConductGateRequestInput } from "@formulary/core/gates/types";

export type DecideConductGateInput = DecideConductGateParams & DecideConductGateRequestInput;

export type DecideConductGateOutput = {};
