/**
 * DataDependencyRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: registry
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DataDependencyRepository Port
 *
 * DDD: Application port for datadependencyrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListDataDependenciesInput, ListDataDependenciesOutput } from "../dto/data-dependency.dto";
export interface DataDependencyRepository {
  listDataDependencies(input: ListDataDependenciesInput): Promise<ListDataDependenciesOutput>;
}

export type { ListDataDependenciesInput, ListDataDependenciesOutput } from "../dto/data-dependency.dto";
