/**
 * RegistryModelRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: registry
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RegistryModelRepository Port
 *
 * DDD: Application port for registrymodelrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListModelRegistrationsInput, ListModelRegistrationsOutput, RegisterModelInput, RegisterModelOutput } from "../dto/registry-model.dto";
export interface RegistryModelRepository {
  listModelRegistrations(input: ListModelRegistrationsInput): Promise<ListModelRegistrationsOutput>;
  registerModel(input: RegisterModelInput): Promise<RegisterModelOutput>;
}

export type { ListModelRegistrationsInput, ListModelRegistrationsOutput, RegisterModelInput, RegisterModelOutput } from "../dto/registry-model.dto";
