/**
 * Benefits DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: benefits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Benefits Domain Module - Composition root
 *
 * DDD: Composition root for benefits domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  ClaimRepositoryAdapter,
  CloseRepositoryAdapter,
} from "@formulary/adapters/benefits";
import { getIdGeneratorService } from "@formulary/adapters";
import type { AdapterDynamoDBClient } from "@formulary/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteClaimBenefit,
  ExecuteCloseBenefitWithFinance,
} from "@formulary/services/benefits/usecases";
// Ports (interfaces)
import type {
  ClaimRepository,
  CloseRepository,
} from "@formulary/services/benefits/ports";

export interface BenefitsDomainModule {
  repos: {
    claims: ClaimRepository;
    closes: CloseRepository;
  };
  useCases: {
    claims: {
      get: ExecuteClaimBenefit;
    };
    closes: {
      get: ExecuteCloseBenefitWithFinance;
    };
  };
}

export function buildBenefitsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): BenefitsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      claims?: ClaimRepository;
      closes?: CloseRepository;
    } = {};

    obj.claims = new ClaimRepositoryAdapter(dynamoClient);
    obj.closes = new CloseRepositoryAdapter(dynamoClient);
    return {
      claims: obj.claims!,
      closes: obj.closes!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    claims: {
      get: new ExecuteClaimBenefit(executionContext, idGenerator, repos.claims),
    },
    closes: {
      get: new ExecuteCloseBenefitWithFinance(executionContext, idGenerator, repos.closes),
    },
  };
  return { repos, useCases: useCases as BenefitsDomainModule["useCases"] };
}
