/**
 * AdjacencyRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: candidates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AdjacencyRepository Port
 *
 * DDD: Application port for adjacencyrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetAdjacentUseCasesInput, GetAdjacentUseCasesOutput } from "../dto/adjacency.dto";
export interface AdjacencyRepository {
  getAdjacentUseCases(input: GetAdjacentUseCasesInput): Promise<GetAdjacentUseCasesOutput>;
}

export type { GetAdjacentUseCasesInput, GetAdjacentUseCasesOutput } from "../dto/adjacency.dto";
