/**
 * ValuePositionRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: candidates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ValuePositionRepository Port
 *
 * DDD: Application port for valuepositionrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { SetValuePositionInput, SetValuePositionOutput } from "../dto/value-position.dto";
export interface ValuePositionRepository {
  setValuePosition(input: SetValuePositionInput): Promise<SetValuePositionOutput>;
}

export type { SetValuePositionInput, SetValuePositionOutput } from "../dto/value-position.dto";
