/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: benefits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./claim-repository.ddb.js";
export * from "./close-repository.ddb.js";
export * from "./claim-repository.adapter.js";
export * from "./close-repository.adapter.js";
