/**
 * ExecuteListDataBlockers - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: readiness
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListDataBlockers Use Case
 *
 * DDD: Application use case for list DataBlocker.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListDataBlockersInput, ListDataBlockersOutput } from "../dto/data-blocker.dto";
import type { ExecutionContextService, IdGeneratorService } from "@formulary/services/_shared/index.js";
import type { DataBlockerRepository } from "../ports";

export class ExecuteListDataBlockers {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly dataBlocker: DataBlockerRepository
  ) {}

  async execute(input: ListDataBlockersInput): Promise<ListDataBlockersOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.rdyId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.dataBlocker.listDataBlockers({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListDataBlockersOutput;
  }
}
