/**
 * ExecuteGetDataReadinessVerdict - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: readiness
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetDataReadinessVerdict Use Case
 *
 * DDD: Application use case for get Readiness.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetDataReadinessVerdictInput, GetDataReadinessVerdictOutput } from "../dto/readiness.dto";
import type { ExecutionContextService, IdGeneratorService } from "@formulary/services/_shared/index.js";
import type { ReadinessRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetDataReadinessVerdict {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly readiness: ReadinessRepository
  ) {}

  async execute(input: GetDataReadinessVerdictInput): Promise<GetDataReadinessVerdictOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.rdyId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).candidateId) {
      throw new ValidationError("candidateId is required");
    }
    const candidateId = (input as any).candidateId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.readiness.getDataReadinessVerdict({ candidateId: candidateId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${candidateId}`);
    }

    return entity as GetDataReadinessVerdictOutput;
  }
}
