/**
 * KillReviewRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: investment
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * KillReviewRepository Port
 *
 * DDD: Application port for killreviewrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ReviewKillCriteriaInput, ReviewKillCriteriaOutput } from "../dto/kill-review.dto";
export interface KillReviewRepository {
  reviewKillCriteria(input: ReviewKillCriteriaInput): Promise<ReviewKillCriteriaOutput>;
}

export type { ReviewKillCriteriaInput, ReviewKillCriteriaOutput } from "../dto/kill-review.dto";
