/**
 * Investment Schemas - Domain schemas barrel export
 *
 * Generated by Schemas Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: investment
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { schemas } from "../openapi/investment.zod.schema.js";

export { schemas };
